'use client';

import { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'th' | 'en' | 'jp';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation data
const translations = {
  th: {
    // NavBar
    'nav.home': 'หน้าแรก',
    'nav.about': 'เกี่ยวกับเรา',
    'nav.services': 'บริการ',
    'nav.products': 'ผลิตภัณฑ์',
    'nav.contact': 'ติดต่อเรา',
    'nav.business_hours': 'เปิดบริการ: จันทร์-ศุกร์ 8:00-17:00',
    'nav.phone': '038-027-473',
    'nav.email': 'info@nagato.co.th',
    
    // Footer
    'footer.company_description': 'บริษัทของเรามุ่งมั่นในการให้บริการที่มีคุณภาพสูงสุด พร้อมด้วยทีมงานมืออาชีพและเทคโนโลยีที่ทันสมัย',
    'footer.quick_links': 'ลิงก์ด่วน',
    'footer.contact_us': 'ติดต่อเรา',
    'footer.location': 'ที่ตั้ง',
    'footer.address_line1': '7/379 หมู่ที่ 6 นิคมอุตสาหกรรมอมตะซิตี้',
    'footer.address_line2': 'ตำบลมาบยางพร อำเภอปลวกแดง',
    'footer.address_line3': 'จังหวัดระยอง 21140',
    'footer.copyright': 'บริษัทของคุณ จำกัด. สงวนลิขสิทธิ์ทุกประการ',
    'footer.privacy': 'นโยบายความเป็นส่วนตัว',
    'footer.terms': 'ข้อกำหนดการใช้งาน',
    'footer.phone': '038-027-473, 062-604-1289',
    'footer.fax': '038-027-475',
    
    // Meta
    'meta.title': 'บริษัทของคุณ - บริการคุณภาพสูง',
    'meta.description': 'บริษัทของเรามุ่งมั่นในการให้บริการที่มีคุณภาพสูงสุด พร้อมด้วยทีมงานมืออาชีพและเทคโนโลยีที่ทันสมัย',
    
    // Home Page
    'home.hero.title': 'ยินดีต้อนรับสู่',
    'home.hero.subtitle': 'NAGATO HEAT TREATMENT (THAILAND) CO.,LTD.',
    'home.hero.description': 'เราให้บริการอบ ชุบ (Heat Treatment) ทุกประเภท ด้วยเทคโนโลยีที่ทันสมัยและทีมงานผู้เชี่ยวชาญ เพื่อเพิ่มคุณภาพและความแข็งแกร่งของวัสดุให้ตรงตามมาตรฐานสากล',
    'home.hero.cta1': 'เริ่มต้นใช้งาน',
    'home.hero.cta2': 'เรียนรู้เพิ่มเติม',
    'home.features.title': 'ทำไมต้องเลือกเรา',
    'home.features.subtitle': 'เรามุ่งมั่นให้บริการอบ ชุบ ที่ดีที่สุด ด้วยเทคโนโลยีที่ทันสมัยและทีมงานผู้เชี่ยวชาญ',
    'home.features.technology.title': 'เทคโนโลยีทันสมัย',
    'home.features.technology.desc': 'เครื่องจักรและอุปกรณ์ที่ทันสมัย ควบคุมด้วยระบบดิจิทัล เพื่อความแม่นยำสูงสุด',
    'home.features.quality.title': 'คุณภาพสูง',
    'home.features.quality.desc': 'มาตรฐานคุณภาพระดับสากล พร้อมใบรับรองคุณภาพ รับประกันผลลัพธ์ที่เหนือความคาดหวัง',
    'home.features.precision.title': 'ความแม่นยำ',
    'home.features.precision.desc': 'ควบคุมอุณหภูมิและเวลาอย่างแม่นยำ ตามมาตรฐานสากล เพื่อผลลัพธ์ที่สม่ำเสมอ',
    'home.features.reliability.title': 'ความน่าเชื่อถือ',
    'home.features.reliability.desc': 'รับประกันคุณภาพและความปลอดภัยของชิ้นงานทุกชิ้น ด้วยระบบตรวจสอบคุณภาพที่เข้มงวด',
    'home.features.innovation.title': 'นวัตกรรม',
    'home.features.innovation.desc': 'พัฒนาอย่างต่อเนื่องด้วยเทคโนโลยีและแนวทางที่ทันสมัย เพื่อตอบสนองความต้องการที่เปลี่ยนแปลงไป',
    'home.features.support.title': 'บริการหลังการขาย',
    'home.features.support.desc': 'ทีมสนับสนุนที่พร้อมช่วยเหลือคุณตลอด 24 ชั่วโมง พร้อมให้คำปรึกษาและแก้ไขปัญหา',
    'home.about.title': 'เกี่ยวกับเรา',
    'home.about.desc1': 'Nagato เป็นบริษัทที่ประกอบกิจการพัฒนา ออกแบบ และให้บริการอบ ชุบ (Heat Treatment) ทุกประเภท ด้วยเทคโนโลยีที่ทันสมัยและทีมงานผู้เชี่ยวชาญ เพื่อเพิ่มคุณภาพและความแข็งแกร่งของวัสดุให้ตรงตามมาตรฐานสากล',
    'home.about.desc2': 'ด้วยความมุ่งมั่นในการให้บริการอบ ชุบ ที่ดีที่สุด เราจึงได้รับความไว้วางใจจากลูกค้าทั่วประเทศ และพร้อมที่จะเป็นส่วนหนึ่งในการขับเคลื่อนอุตสาหกรรมของคุณไปสู่ความสำเร็จ',
    'home.about.cta': 'เรียนรู้เพิ่มเติม',
    'home.about.stats.customers': 'ลูกค้าที่ไว้วางใจ',
    'home.about.stats.quality': 'คุณภาพรับประกัน',
    'home.about.stats.support': 'บริการสนับสนุน',
    'home.about.stats.experience': 'ปีประสบการณ์',
    'home.cta.title': 'พร้อมเริ่มต้นแล้วหรือยัง?',
    'home.cta.description': 'เข้าร่วมกับเราและสัมผัสประสบการณ์การอบ ชุบ ที่ดีที่สุด พร้อมรับการสนับสนุนจากทีมงานมืออาชีพ',
    'home.cta.button1': 'เริ่มใช้งานฟรี',
    'home.cta.button2': 'ติดต่อเรา',
    'home.cta.trust': 'เชื่อถือโดยบริษัทชั้นนำ',
    'home.cta.trust1': 'อุตสาหกรรมยานยนต์',
    'home.cta.trust2': 'อุตสาหกรรมเครื่องจักร',
    'home.cta.trust3': 'อุตสาหกรรมอากาศยาน',
    'home.cta.trust4': 'อุตสาหกรรมพลังงาน',
    
    // News Section
    'home.news.title': 'ข่าวสารและอัพเดท',
    'home.news.subtitle': 'ติดตามข่าวสารล่าสุดเกี่ยวกับเทคโนโลยีการอบ ชุบ และการพัฒนาของบริษัท',
    'home.news.readMore': 'อ่านเพิ่มเติม',
    'home.news.viewAll': 'ดูข่าวสารทั้งหมด',
    'home.news.item1.title': 'เทคโนโลยีการอบ ชุบ ใหม่ล่าสุด',
    'home.news.item1.description': 'บริษัทได้นำเทคโนโลยีการอบ ชุบ ที่ทันสมัยที่สุดมาใช้ เพื่อเพิ่มประสิทธิภาพและคุณภาพของงานให้สูงขึ้น',
    'home.news.item1.category': 'เทคโนโลยี',
    'home.news.item2.title': 'ขยายกำลังการผลิต',
    'home.news.item2.description': 'เพื่อตอบสนองความต้องการที่เพิ่มขึ้น บริษัทได้ขยายกำลังการผลิตและเพิ่มเครื่องจักรใหม่',
    'home.news.item2.category': 'ข่าวสาร',
    'home.news.item3.title': 'รับใบรับรองมาตรฐาน ISO',
    'home.news.item3.description': 'บริษัทได้รับใบรับรองมาตรฐาน ISO 9001:2015 ซึ่งแสดงถึงความมุ่งมั่นในการให้บริการที่มีคุณภาพ',
    'home.news.item3.category': 'ความสำเร็จ',
    'home.news.item4.title': 'ร่วมงานแสดงสินค้าอุตสาหกรรม',
    'home.news.item4.description': 'บริษัทเข้าร่วมงานแสดงสินค้าอุตสาหกรรมเพื่อนำเสนอเทคโนโลยีและบริการใหม่ๆ ให้กับลูกค้า',
    'home.news.item4.category': 'กิจกรรม',
    'home.news.item5.title': 'อบรมพนักงานด้านความปลอดภัย',
    'home.news.item5.description': 'จัดอบรมพนักงานด้านความปลอดภัยในการทำงาน เพื่อให้มั่นใจในความปลอดภัยของทุกคน',
    'home.news.item5.category': 'การพัฒนาบุคลากร',
    
    // News Page
    'news.pageTitle': 'ข่าวสารทั้งหมด',
    'news.pageSubtitle': 'ติดตามข่าวสารและอัพเดทล่าสุดจากบริษัท',
    'news.backToHome': 'กลับไปหน้าแรก',
    'news.readMore': 'อ่านเพิ่มเติม',
    'news.close': 'ปิด',
    'news.item1.title': 'เทคโนโลยีการอบ ชุบ ใหม่ล่าสุด',
    'news.item1.description': 'บริษัทได้นำเทคโนโลยีการอบ ชุบ ที่ทันสมัยที่สุดมาใช้ เพื่อเพิ่มประสิทธิภาพและคุณภาพของงานให้สูงขึ้น',
    'news.item1.fullContent': 'บริษัท NAGATO HEAT TREATMENT (THAILAND) CO.,LTD. ได้นำเทคโนโลยีการอบ ชุบ ที่ทันสมัยที่สุดมาใช้ในกระบวนการผลิต เพื่อเพิ่มประสิทธิภาพและคุณภาพของงานให้สูงขึ้น โดยเทคโนโลยีใหม่นี้จะช่วยให้การควบคุมอุณหภูมิและเวลามีความแม่นยำมากขึ้น พร้อมทั้งลดการใช้พลังงานและเพิ่มความปลอดภัยในการทำงาน',
    'news.item1.author': 'ทีมข่าวสาร',
    'news.item2.title': 'ขยายกำลังการผลิต',
    'news.item2.description': 'เพื่อตอบสนองความต้องการที่เพิ่มขึ้น บริษัทได้ขยายกำลังการผลิตและเพิ่มเครื่องจักรใหม่',
    'news.item2.fullContent': 'เนื่องจากการเติบโตของธุรกิจและความต้องการที่เพิ่มขึ้น บริษัทได้ตัดสินใจขยายกำลังการผลิตโดยการเพิ่มเครื่องจักรและอุปกรณ์ใหม่ที่ทันสมัย พร้อมทั้งขยายพื้นที่การผลิต เพื่อให้สามารถรองรับลูกค้าได้มากขึ้นและส่งมอบงานได้ตรงตามกำหนดเวลา',
    'news.item2.author': 'ฝ่ายการผลิต',
    'news.item3.title': 'รับใบรับรองมาตรฐาน ISO',
    'news.item3.description': 'บริษัทได้รับใบรับรองมาตรฐาน ISO 9001:2015 ซึ่งแสดงถึงความมุ่งมั่นในการให้บริการที่มีคุณภาพ',
    'news.item3.fullContent': 'บริษัทได้รับใบรับรองมาตรฐาน ISO 9001:2015 ซึ่งเป็นมาตรฐานสากลสำหรับระบบการจัดการคุณภาพ การได้รับใบรับรองนี้แสดงถึงความมุ่งมั่นของบริษัทในการให้บริการที่มีคุณภาพสูงสุดและพัฒนาระบบการทำงานให้มีประสิทธิภาพมากขึ้น',
    'news.item3.author': 'ฝ่ายคุณภาพ',
    'news.item4.title': 'ร่วมงานแสดงสินค้าอุตสาหกรรม',
    'news.item4.description': 'บริษัทเข้าร่วมงานแสดงสินค้าอุตสาหกรรมเพื่อนำเสนอเทคโนโลยีและบริการใหม่ๆ ให้กับลูกค้า',
    'news.item4.fullContent': 'บริษัทได้เข้าร่วมงานแสดงสินค้าอุตสาหกรรมครั้งสำคัญ เพื่อนำเสนอเทคโนโลยีและบริการใหม่ๆ ให้กับลูกค้าและพันธมิตรทางธุรกิจ งานนี้เป็นโอกาสที่ดีในการสร้างเครือข่ายและแสดงศักยภาพของบริษัทในด้านการอบ ชุบ',
    'news.item4.author': 'ฝ่ายการตลาด',
    'news.item5.title': 'อบรมพนักงานด้านความปลอดภัย',
    'news.item5.description': 'จัดอบรมพนักงานด้านความปลอดภัยในการทำงาน เพื่อให้มั่นใจในความปลอดภัยของทุกคน',
    'news.item5.fullContent': 'บริษัทได้จัดอบรมพนักงานด้านความปลอดภัยในการทำงานเป็นประจำ เพื่อให้มั่นใจในความปลอดภัยของทุกคนและลดความเสี่ยงในการเกิดอุบัติเหตุ การอบรมครอบคลุมทั้งทฤษฎีและการปฏิบัติจริง',
    'news.item5.author': 'ฝ่ายความปลอดภัย',
    'news.item6.title': 'เปิดศูนย์วิจัยและพัฒนาใหม่',
    'news.item6.description': 'บริษัทเปิดศูนย์วิจัยและพัฒนาใหม่เพื่อพัฒนานวัตกรรมในด้านการอบ ชุบ',
    'news.item6.fullContent': 'บริษัทได้เปิดศูนย์วิจัยและพัฒนาใหม่ที่ทันสมัย เพื่อพัฒนานวัตกรรมในด้านการอบ ชุบ และสร้างเทคโนโลยีใหม่ๆ ที่จะช่วยเพิ่มประสิทธิภาพการทำงานและคุณภาพของผลิตภัณฑ์',
    'news.item6.author': 'ฝ่ายวิจัยและพัฒนา',
    'news.item7.title': 'ร่วมมือกับมหาวิทยาลัย',
    'news.item7.description': 'บริษัทได้ร่วมมือกับมหาวิทยาลัยในการวิจัยและพัฒนานวัตกรรมใหม่',
    'news.item7.fullContent': 'บริษัทได้ลงนามความร่วมมือกับมหาวิทยาลัยชั้นนำในการวิจัยและพัฒนานวัตกรรมใหม่ในด้านการอบ ชุบ ความร่วมมือนี้จะช่วยให้บริษัทสามารถเข้าถึงความรู้และเทคโนโลยีใหม่ๆ ได้มากขึ้น',
    'news.item7.author': 'ฝ่ายวิชาการ',
    'news.item8.title': 'รับรางวัลคุณภาพแห่งปี',
    'news.item8.description': 'บริษัทได้รับรางวัลคุณภาพแห่งปีจากสมาคมอุตสาหกรรม',
    'news.item8.fullContent': 'บริษัทได้รับรางวัลคุณภาพแห่งปีจากสมาคมอุตสาหกรรม ซึ่งเป็นรางวัลที่แสดงถึงความมุ่งมั่นในการให้บริการที่มีคุณภาพสูงสุดและความสำเร็จในการพัฒนาธุรกิจอย่างยั่งยืน',
    'news.item8.author': 'ฝ่ายบริหาร',
    
    // About Page
    'about.hero.title': 'เกี่ยวกับเรา',
    'about.hero.description': 'เราคือบริษัทที่ประกอบกิจการพัฒนา ออกแบบ และให้บริการอบ ชุบ (Heat Treatment) ทุกประเภท ด้วยเทคโนโลยีที่ทันสมัยและทีมงานผู้เชี่ยวชาญ เพื่อเพิ่มคุณภาพและความแข็งแกร่งของวัสดุให้ตรงตามมาตรฐานสากล',
    'about.hero.technology.title': 'เทคโนโลยีทันสมัย',
    'about.hero.technology.desc': 'เครื่องจักรและอุปกรณ์ที่ทันสมัย ควบคุมด้วยระบบดิจิทัล',
    'about.hero.quality.title': 'คุณภาพสูง',
    'about.hero.quality.desc': 'มาตรฐานคุณภาพระดับสากล พร้อมใบรับรองคุณภาพ',
    'about.hero.expertise.title': 'ความเชี่ยวชาญ',
    'about.hero.expertise.desc': 'ทีมงานผู้เชี่ยวชาญที่มีประสบการณ์สูงในด้านการอบ ชุบ',
    'about.mission.title': 'พันธกิจของเรา',
    'about.mission.main.title': 'พันธกิจหลัก',
    'about.mission.main.desc': 'มุ่งมั่นในการให้บริการอบ ชุบ (Heat Treatment) ที่มีคุณภาพสูงสุด พร้อมสร้างความพึงพอใจให้กับลูกค้าทุกท่าน ด้วยการนำเทคโนโลยีที่ทันสมัยมาประยุกต์ใช้ในการพัฒนาคุณภาพวัสดุ',
    'about.mission.vision.title': 'วิสัยทัศน์',
    'about.mission.vision.desc': 'เป็นผู้นำในอุตสาหกรรมการอบ ชุบ ที่ลูกค้าไว้วางใจ ด้วยการพัฒนาอย่างต่อเนื่อง และการสร้างสรรค์นวัตกรรมใหม่ๆ เพื่อตอบสนองความต้องการของอุตสาหกรรมที่เปลี่ยนแปลงไป',
    'about.mission.values.title': 'ค่านิยม',
    'about.mission.values.desc': 'ความแม่นยำ ความรับผิดชอบ และการทำงานเป็นทีม พร้อมทั้งการพัฒนาตนเองอย่างต่อเนื่องเพื่อให้บริการอบ ชุบ ที่ดีที่สุด',
    'about.mission.commitment.title': 'ความมุ่งมั่นของเรา',
    'about.mission.commitment.desc': 'เรามุ่งมั่นที่จะเป็นส่วนหนึ่งในการขับเคลื่อนอุตสาหกรรมของคุณให้เติบโตอย่างยั่งยืน ด้วยการให้บริการอบ ชุบ ที่เหนือความคาดหวังและสร้างความไว้วางใจในระยะยาว',
    'about.values.title': 'ค่านิยมหลักของเรา',
    'about.values.subtitle': 'ค่านิยมที่เรายึดถือและปฏิบัติในทุกการทำงาน เพื่อสร้างความไว้วางใจ และความพึงพอใจให้กับลูกค้าและพนักงานทุกท่าน',
    'about.values.quality.title': 'คุณภาพ',
    'about.values.quality.desc': 'มุ่งมั่นในการให้บริการอบ ชุบ ที่มีคุณภาพสูงสุดในทุกขั้นตอน',
    'about.values.technology.title': 'เทคโนโลยี',
    'about.values.technology.desc': 'ใช้เครื่องจักรและอุปกรณ์ที่ทันสมัย ควบคุมด้วยระบบดิจิทัล',
    'about.values.precision.title': 'ความแม่นยำ',
    'about.values.precision.desc': 'ควบคุมอุณหภูมิและเวลาอย่างแม่นยำ ตามมาตรฐานสากล',
    'about.values.reliability.title': 'ความน่าเชื่อถือ',
    'about.values.reliability.desc': 'รับประกันคุณภาพและความปลอดภัยของชิ้นงานทุกชิ้น',
    'about.values.innovation.title': 'นวัตกรรม',
    'about.values.innovation.desc': 'พัฒนาอย่างต่อเนื่องด้วยเทคโนโลยีและแนวทางที่ทันสมัย',
    'about.values.excellence.title': 'ความเป็นเลิศ',
    'about.values.excellence.desc': 'มุ่งมั่นสู่ความเป็นเลิศในการให้บริการอบ ชุบ ทุกประเภท',
    'about.values.commitment.title': 'พันธสัญญาของเรา',
    'about.values.commitment.desc': 'เรามุ่งมั่นที่จะดำเนินธุรกิจด้วยความแม่นยำ โปร่งใส และรับผิดชอบ พร้อมทั้งพัฒนาตนเองอย่างต่อเนื่องเพื่อให้บริการอบ ชุบ ที่ดีที่สุดแก่ลูกค้าทุกท่าน',
    
    // Services Page
    'service.hero.title': 'บริการอบ ชุบ (Heat Treatment)',
    'service.hero.description': 'ให้บริการอบ ชุบ ทุกประเภท ด้วยเทคโนโลยีที่ทันสมัยและทีมงานผู้เชี่ยวชาญ เพื่อเพิ่มคุณภาพและความแข็งแกร่งของวัสดุให้ตรงตามมาตรฐานสากล',
    'service.hero.quality.title': 'คุณภาพสูง',
    'service.hero.quality.desc': 'มาตรฐานคุณภาพระดับสากล พร้อมใบรับรองคุณภาพ',
    'service.hero.speed.title': 'รวดเร็ว',
    'service.hero.speed.desc': 'ส่งมอบงานตรงเวลา พร้อมคุณภาพที่รับประกัน',
    'service.hero.support.title': 'บริการหลังการขาย',
    'service.hero.support.desc': 'ทีมสนับสนุนที่พร้อมช่วยเหลือตลอด 24 ชั่วโมง',

    'service.features.title': 'จุดเด่นของบริการอบ ชุบ',
    'service.features.subtitle': 'เราให้บริการอบ ชุบ ด้วยเทคโนโลยีที่ทันสมัยและทีมงานผู้เชี่ยวชาญ เพื่อให้ได้ผลลัพธ์ที่ดีที่สุด',
    'service.features.performance.title': 'เทคโนโลยีทันสมัย',
    'service.features.performance.desc': 'เครื่องจักรและอุปกรณ์ที่ทันสมัย ควบคุมด้วยระบบดิจิทัล',
    'service.features.security.title': 'ความปลอดภัย',
    'service.features.security.desc': 'ระบบความปลอดภัยที่ได้มาตรฐาน รับประกันความปลอดภัยของชิ้นงาน',
    'service.features.reliability.title': 'ความแม่นยำ',
    'service.features.reliability.desc': 'ควบคุมอุณหภูมิและเวลาอย่างแม่นยำ ตามมาตรฐานสากล',
    'service.features.mobile.title': 'บริการครบวงจร',
    'service.features.mobile.desc': 'ให้บริการอบ ชุบ ครบทุกประเภท เพื่อตอบสนองความต้องการของอุตสาหกรรมต่างๆ',
    'service.features.analytics.title': 'ตรวจสอบคุณภาพ',
    'service.features.analytics.desc': 'ตรวจสอบคุณภาพและทดสอบคุณสมบัติหลังการอบ ชุบ',
    'service.features.support.title': 'บริการหลังการขาย',
    'service.features.support.desc': 'ทีมสนับสนุนที่พร้อมช่วยเหลือตลอด 24 ชั่วโมง',

    'service.process.title': 'กระบวนการทำงาน',
    'service.process.subtitle': 'ขั้นตอนการทำงานที่ชัดเจน โปร่งใส และมีประสิทธิภาพ เพื่อให้ได้ผลลัพธ์ที่ดีที่สุด',
    'service.process.consultation.title': 'ปรึกษาและวิเคราะห์',
    'service.process.consultation.desc': 'วิเคราะห์ความต้องการและกำหนดขอบเขตการทำงาน',
    'service.process.planning.title': 'ตรวจสอบและวิเคราะห์',
    'service.process.planning.desc': 'ตรวจสอบวัสดุและวิเคราะห์คุณสมบัติก่อนการอบ ชุบ',
    'service.process.development.title': 'การอบ ชุบ',
    'service.process.development.desc': 'ดำเนินการอบ ชุบ ตามมาตรฐานที่กำหนด',
    'service.process.delivery.title': 'ส่งมอบงาน',
    'service.process.delivery.desc': 'ส่งมอบงานพร้อมรายงานผลการทดสอบและใบรับรองคุณภาพ',

    'service.pricing.title': 'แพ็กเกจบริการอบ ชุบ',
    'service.pricing.subtitle': 'เลือกแพ็กเกจที่เหมาะกับความต้องการของคุณ หรือปรับแต่งได้ตามต้องการ',
    'service.pricing.basic.title': 'บริการพื้นฐาน',
    'service.pricing.basic.desc': 'เหมาะสำหรับการอบ ชุบ ขนาดเล็ก',
    'service.pricing.basic.feature1': 'การอบอ่อน (Annealing)',
    'service.pricing.basic.feature2': 'การชุบแข็ง (Quenching)',
    'service.pricing.basic.feature3': 'การอบคืน (Tempering)',
    'service.pricing.basic.feature4': 'รายงานผลการทดสอบ',
    'service.pricing.basic.price': '฿500/กก.',
    'service.pricing.pro.title': 'บริการมาตรฐาน',
    'service.pricing.pro.desc': 'เหมาะสำหรับการอบ ชุบ ขนาดกลาง',
    'service.pricing.pro.feature1': 'ฟีเจอร์ทั้งหมดของพื้นฐาน',
    'service.pricing.pro.feature2': 'การอบปกติ (Normalizing)',
    'service.pricing.pro.feature3': 'การชุบคาร์บอน (Carburizing)',
    'service.pricing.pro.feature4': 'การชุบไนโตรเจน (Nitriding)',
    'service.pricing.pro.feature5': 'ใบรับรองคุณภาพ',
    'service.pricing.pro.price': '฿800/กก.',
    'service.pricing.enterprise.title': 'บริการพิเศษ',
    'service.pricing.enterprise.desc': 'สำหรับการอบ ชุบ ขนาดใหญ่และความต้องการเฉพาะ',
    'service.pricing.enterprise.feature1': 'การออกแบบกระบวนการเฉพาะ',
    'service.pricing.enterprise.feature2': 'การปรับแต่งตามความต้องการ',
    'service.pricing.enterprise.feature3': 'การอบ ชุบ ครบวงจร',
    'service.pricing.enterprise.feature4': 'อบรมและให้คำปรึกษา',
    'service.pricing.enterprise.feature5': 'ที่ปรึกษาประจำ',
    'service.pricing.enterprise.feature6': 'รับประกันคุณภาพ',
    'service.pricing.enterprise.price': 'ติดต่อเรา',
    'service.pricing.note': 'ราคาด้านบนเป็นราคาโดยประมาณ สามารถปรับตามความต้องการได้',
    'service.pricing.contact': 'ติดต่อฝ่ายขาย',

    'service.card.popular': 'ยอดนิยม',
    'service.card.perMonth': 'ต่อกิโลกรัม',
    'service.card.learnMore': 'ดูรายละเอียด',

    // Products Page
    'product.hero.title': 'บริการอบ ชุบ (Heat Treatment)',
    'product.hero.description': 'ให้บริการอบ ชุบ ทุกประเภท ด้วยเทคโนโลยีที่ทันสมัยและทีมงานผู้เชี่ยวชาญ เพื่อเพิ่มคุณภาพและความแข็งแกร่งของวัสดุให้ตรงตามมาตรฐานสากล',
    'product.hero.heat.title': 'เทคโนโลยีความร้อน',
    'product.hero.heat.desc': 'ระบบควบคุมอุณหภูมิที่แม่นยำ',
    'product.hero.treatment.title': 'การอบ ชุบ',
    'product.hero.treatment.desc': 'กระบวนการที่ได้มาตรฐานสากล',
    'product.hero.quality.title': 'คุณภาพสูง',
    'product.hero.quality.desc': 'รับประกันคุณภาพทุกชิ้นงาน',

    'product.showcase.title': 'ประเภทการอบ ชุบ',
    'product.showcase.subtitle': 'บริการอบ ชุบ ครบทุกประเภท เพื่อตอบสนองความต้องการของอุตสาหกรรมต่างๆ',
    'product.showcase.annealing.title': 'การอบอ่อน (Annealing)',
    'product.showcase.annealing.desc': 'กระบวนการอบอ่อนเพื่อลดความแข็งและปรับปรุงโครงสร้างผลึกของโลหะ',
    'product.showcase.annealing.feature1': 'ลดความแข็งของโลหะ',
    'product.showcase.annealing.feature2': 'ปรับปรุงโครงสร้างผลึก',
    'product.showcase.annealing.feature3': 'เพิ่มความเหนียว',
    'product.showcase.annealing.feature4': 'ลดความเค้นภายใน',
    'product.showcase.quenching.title': 'การชุบแข็ง (Quenching)',
    'product.showcase.quenching.desc': 'กระบวนการชุบแข็งเพื่อเพิ่มความแข็งและความต้านทานการสึกหรอ',
    'product.showcase.quenching.feature1': 'เพิ่มความแข็งสูงสุด',
    'product.showcase.quenching.feature2': 'ต้านทานการสึกหรอ',
    'product.showcase.quenching.feature3': 'เพิ่มความแข็งแรง',
    'product.showcase.quenching.feature4': 'ปรับปรุงคุณสมบัติเชิงกล',
    'product.showcase.tempering.title': 'การอบคืน (Tempering)',
    'product.showcase.tempering.desc': 'กระบวนการอบคืนเพื่อลดความเปราะและปรับสมดุลความแข็งกับความเหนียว',
    'product.showcase.tempering.feature1': 'ลดความเปราะ',
    'product.showcase.tempering.feature2': 'ปรับสมดุลความแข็ง',
    'product.showcase.tempering.feature3': 'เพิ่มความเหนียว',
    'product.showcase.tempering.feature4': 'ลดความเค้นภายใน',
    'product.showcase.normalizing.title': 'การอบปกติ (Normalizing)',
    'product.showcase.normalizing.desc': 'กระบวนการอบปกติเพื่อปรับปรุงโครงสร้างผลึกและคุณสมบัติเชิงกล',
    'product.showcase.normalizing.feature1': 'ปรับปรุงโครงสร้างผลึก',
    'product.showcase.normalizing.feature2': 'เพิ่มความแข็งแรง',
    'product.showcase.normalizing.feature3': 'ปรับปรุงคุณสมบัติเชิงกล',
    'product.showcase.normalizing.feature4': 'ลดความเค้นภายใน',
    'product.showcase.carburizing.title': 'การชุบคาร์บอน (Carburizing)',
    'product.showcase.carburizing.desc': 'กระบวนการชุบคาร์บอนเพื่อเพิ่มความแข็งที่ผิวและความต้านทานการสึกหรอ',
    'product.showcase.carburizing.feature1': 'เพิ่มความแข็งที่ผิว',
    'product.showcase.carburizing.feature2': 'ต้านทานการสึกหรอสูง',
    'product.showcase.carburizing.feature3': 'เพิ่มความแข็งแรง',
    'product.showcase.carburizing.feature4': 'ปรับปรุงคุณสมบัติผิว',
    'product.showcase.nitriding.title': 'การชุบไนโตรเจน (Nitriding)',
    'product.showcase.nitriding.desc': 'กระบวนการชุบไนโตรเจนเพื่อเพิ่มความแข็งที่ผิวและความต้านทานการกัดกร่อน',
    'product.showcase.nitriding.feature1': 'เพิ่มความแข็งที่ผิวสูง',
    'product.showcase.nitriding.feature2': 'ต้านทานการกัดกร่อน',
    'product.showcase.nitriding.feature3': 'เพิ่มความแข็งแรง',
    'product.showcase.nitriding.feature4': 'ปรับปรุงคุณสมบัติผิว',

    'product.features.title': 'จุดเด่นของเรา',
    'product.features.subtitle': 'เราให้บริการอบ ชุบ ด้วยเทคโนโลยีที่ทันสมัยและทีมงานผู้เชี่ยวชาญ เพื่อให้ได้ผลลัพธ์ที่ดีที่สุด',
    'product.features.quality.title': 'คุณภาพสูง',
    'product.features.quality.desc': 'มาตรฐานคุณภาพระดับสากล พร้อมใบรับรองคุณภาพ',
    'product.features.speed.title': 'รวดเร็ว',
    'product.features.speed.desc': 'ส่งมอบงานตรงเวลา พร้อมคุณภาพที่รับประกัน',
    'product.features.technology.title': 'เทคโนโลยีทันสมัย',
    'product.features.technology.desc': 'เครื่องจักรและอุปกรณ์ที่ทันสมัย ควบคุมด้วยระบบดิจิทัล',
    'product.features.precision.title': 'ความแม่นยำ',
    'product.features.precision.desc': 'ควบคุมอุณหภูมิและเวลาอย่างแม่นยำ ตามมาตรฐานสากล',
    'product.features.support.title': 'บริการหลังการขาย',
    'product.features.support.desc': 'ทีมสนับสนุนที่พร้อมช่วยเหลือตลอด 24 ชั่วโมง',
    'product.features.security.title': 'ความปลอดภัย',
    'product.features.security.desc': 'ระบบความปลอดภัยที่ได้มาตรฐาน รับประกันความปลอดภัยของชิ้นงาน',

    'product.process.title': 'กระบวนการทำงาน',
    'product.process.subtitle': 'ขั้นตอนการทำงานที่ชัดเจน โปร่งใส และมีประสิทธิภาพ เพื่อให้ได้ผลลัพธ์ที่ดีที่สุด',
    'product.process.consultation.title': 'ปรึกษาและวิเคราะห์',
    'product.process.consultation.desc': 'วิเคราะห์ความต้องการและกำหนดขอบเขตการทำงาน',
    'product.process.analysis.title': 'ตรวจสอบและวิเคราะห์',
    'product.process.analysis.desc': 'ตรวจสอบวัสดุและวิเคราะห์คุณสมบัติก่อนการอบ ชุบ',
    'product.process.treatment.title': 'การอบ ชุบ',
    'product.process.treatment.desc': 'ดำเนินการอบ ชุบ ตามมาตรฐานที่กำหนด',
    'product.process.quality.title': 'ตรวจสอบคุณภาพ',
    'product.process.quality.desc': 'ตรวจสอบคุณภาพและทดสอบคุณสมบัติหลังการอบ ชุบ',
    'product.process.delivery.title': 'ส่งมอบงาน',
    'product.process.delivery.desc': 'ส่งมอบงานพร้อมรายงานผลการทดสอบและใบรับรองคุณภาพ',

    'product.parts.title': 'แกลเลอรี่ชิ้นส่วนของเรา',
    'product.parts.subtitle': 'ชมชิ้นส่วนและส่วนประกอบที่ผลิตด้วยคุณภาพสูงของเรา',
    'product.parts.overview.title': 'ภาพรวมชิ้นส่วน',
    'product.parts.overview.desc': 'ชิ้นส่วนที่ผลิตด้วยคุณภาพสูง',
    'product.parts.part2.title': 'ชิ้นส่วนความแม่นยำ 2',
    'product.parts.part2.desc': 'ผลิตด้วยความแม่นยำสูง',
    'product.parts.part3.title': 'ชิ้นส่วนขั้นสูง 3',
    'product.parts.part3.desc': 'เทคโนโลยีการผลิตขั้นสูง',

    // Contact Page
    'contact.hero.title': 'ติดต่อเรา',
    'contact.hero.description': 'เราพร้อมให้บริการและตอบคำถามทุกข้อสงสัย ติดต่อเราวันนี้เพื่อรับคำปรึกษาฟรี',
    'contact.form.title': 'ส่งข้อความถึงเรา',
    'contact.form.description': 'กรอกข้อมูลด้านล่าง เราจะติดต่อกลับภายใน 24 ชั่วโมง',
    'contact.form.name': 'ชื่อ-นามสกุล',
    'contact.form.name_placeholder': 'กรอกชื่อ-นามสกุลของคุณ',
    'contact.form.email': 'อีเมล',
    'contact.form.email_placeholder': 'กรอกอีเมลของคุณ',
    'contact.form.phone': 'เบอร์โทรศัพท์',
    'contact.form.phone_placeholder': 'กรอกเบอร์โทรศัพท์ของคุณ',
    'contact.form.company': 'บริษัท',
    'contact.form.company_placeholder': 'กรอกชื่อบริษัทของคุณ',
    'contact.form.subject': 'หัวข้อ',
    'contact.form.subject_placeholder': 'เลือกหัวข้อที่ต้องการติดต่อ',
    'contact.form.subject_general': 'คำถามทั่วไป',
    'contact.form.subject_support': 'ขอความช่วยเหลือ',
    'contact.form.subject_sales': 'สอบถามราคา',
    'contact.form.subject_partnership': 'ความร่วมมือ',
    'contact.form.subject_other': 'อื่นๆ',
    'contact.form.message': 'ข้อความ',
    'contact.form.message_placeholder': 'กรอกรายละเอียดที่ต้องการติดต่อ',
    'contact.form.submit': 'ส่งข้อความ',
    'contact.form.submitting': 'กำลังส่ง...',
    'contact.form.success': 'ส่งข้อความสำเร็จ! เราจะติดต่อกลับโดยเร็วที่สุด',
    'contact.form.error': 'เกิดข้อผิดพลาด กรุณาลองใหม่อีกครั้ง',
    'contact.info.title': 'ข้อมูลติดต่อ',
    'contact.info.description': 'ติดต่อเราได้หลายช่องทาง เราพร้อมให้บริการและตอบคำถามทุกข้อสงสัย',
    'contact.info.email.title': 'อีเมล',
    'contact.info.email.description': 'ส่งอีเมลถึงเราได้ตลอด 24 ชั่วโมง',
    'contact.info.phone.title': 'โทรศัพท์',
    'contact.info.phone.description': 'โทรหาเราในเวลาทำการ',
    'contact.info.address.title': 'ที่อยู่',
    'contact.info.address.description': 'เยี่ยมชมสำนักงานของเรา',
    'contact.info.hours.title': 'เวลาทำการ',
    'contact.info.hours.description': 'เวลาที่เราพร้อมให้บริการ',
    'contact.info.social.title': 'ติดตามเรา',
    'contact.map.title': 'แผนที่และเส้นทาง',
    'contact.map.description': 'ค้นหาเส้นทางมาสำนักงานของเราได้ง่ายๆ',
    'contact.map.placeholder.title': 'แผนที่',
    'contact.map.placeholder.description': 'แผนที่จะแสดงที่นี่',
    'contact.map.placeholder.button': 'เปิดแผนที่',
    'contact.map.directions.title': 'เส้นทางมา',
    'contact.map.directions.bts': 'BTS อโศก - ทางออก 6',
    'contact.map.directions.mrt': 'MRT สุขุมวิท - ทางออก 3',
    'contact.map.directions.parking': 'ที่จอดรถในอาคาร',
    'contact.map.nearby.title': 'สถานที่ใกล้เคียง',
    'contact.map.nearby.terminal21': 'เทอร์มินอล 21',
    'contact.map.nearby.emquartier': 'เอ็มควอเทียร์',
    'contact.map.nearby.benjasiri': 'สวนเบญจกิติ',
    'contact.map.nearby.lumpini': 'สวนลุมพินี',
    'contact.company.name': 'NAGATO HEAT TREATMENT (THAILAND) CO.,LTD.',
    'contact.company.address.title': 'ที่ตั้ง',
    'contact.company.phone.title': 'โทรศัพท์',
    'contact.company.hours.title': 'เวลาทำการ',
    'contact.company.address.detail': '7/379 หมู่ที่ 6 นิคมอุตสาหกรรมอมตะซิตี้<br />ตำบลมาบยางพร อำเภอปลวกแดง<br />จังหวัดระยอง 21140',
    'contact.company.phone.detail': '038-027-473<br />062-604-1289<br /><span class="text-sky-600 font-medium">038-027-475 (แฟกซ์)</span>',
    'contact.company.hours.detail': 'จันทร์ - ศุกร์: 8:00 - 17:00<br />เสาร์: 8:00 - 12:00<br />อาทิตย์: ปิดบริการ',
  },
  en: {
    // NavBar
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.services': 'Services',
    'nav.products': 'Products',
    'nav.contact': 'Contact',
    'nav.business_hours': 'Business Hours: Mon-Fri 8:00-17:00',
    'nav.phone': '038-027-473',
    'nav.email': 'info@nagato.co.th',
    
    // Footer
    'footer.company_description': 'Our company is committed to providing the highest quality services with professional teams and modern technology.',
    'footer.quick_links': 'Quick Links',
    'footer.contact_us': 'Contact Us',
    'footer.location': 'Location',
    'footer.address_line1': '7/379 Moo 6 Amata City Industrial Estate',
    'footer.address_line2': 'Tambon Mab Yang Porn, Amphur Pluak Daeng',
    'footer.address_line3': 'Rayong Province 21140',
    'footer.copyright': 'Your Company Ltd. All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.phone': '038-027-473, 062-604-1289',
    'footer.fax': '038-027-475',
    
    // Meta
    'meta.title': 'Your Company - High Quality Services',
    'meta.description': 'Our company is committed to providing the highest quality services with professional teams and modern technology.',
    
    // Home Page
    'home.hero.title': 'Welcome to',
    'home.hero.subtitle': 'NAGATO HEAT TREATMENT (THAILAND) CO.,LTD.',
    'home.hero.description': 'We provide all types of heat treatment services with modern technology and expert teams to enhance material quality and strength according to international standards.',
    'home.hero.cta1': 'Get Started',
    'home.hero.cta2': 'Learn More',
    'home.features.title': 'Why Choose Us',
    'home.features.subtitle': 'We are committed to providing the best heat treatment service with modern technology and expert teams.',
    'home.features.technology.title': 'Modern Technology',
    'home.features.technology.desc': 'Modern machinery and equipment controlled by digital systems for maximum precision.',
    'home.features.quality.title': 'High Quality',
    'home.features.quality.desc': 'International quality standards with quality certificates, guaranteeing results that exceed expectations.',
    'home.features.precision.title': 'Precision',
    'home.features.precision.desc': 'Precise temperature and time control according to international standards for consistent results.',
    'home.features.reliability.title': 'Reliability',
    'home.features.reliability.desc': 'Guaranteeing quality and safety of every workpiece with strict quality inspection systems.',
    'home.features.innovation.title': 'Innovation',
    'home.features.innovation.desc': 'Continuous development with modern technology and approaches to meet changing needs.',
    'home.features.support.title': 'After-Sales Service',
    'home.features.support.desc': 'Support team ready to help you 24/7 with consultation and problem-solving.',
    'home.about.title': 'About Us',
    'home.about.desc1': 'Nagato is a company engaged in development, design, and providing all types of heat treatment services with modern technology and expert teams to enhance material quality and strength according to international standards.',
    'home.about.desc2': 'With our commitment to providing the best heat treatment service, we have gained trust from customers nationwide and are ready to be part of driving your industry to success.',
    'home.about.cta': 'Learn More',
    'home.about.stats.customers': 'Trusted Customers',
    'home.about.stats.quality': 'Quality Guaranteed',
    'home.about.stats.support': 'Support Service',
    'home.about.stats.experience': 'Years Experience',
    'home.cta.title': 'Ready to Get Started?',
    'home.cta.description': 'Join us and experience the best heat treatment service with support from our professional team.',
    'home.cta.button1': 'Start Free',
    'home.cta.button2': 'Contact Us',
    'home.cta.trust': 'Trusted by Leading Companies',
    'home.cta.trust1': 'Automotive Industry',
    'home.cta.trust2': 'Machinery Industry',
    'home.cta.trust3': 'Aerospace Industry',
    'home.cta.trust4': 'Energy Industry',
    
    // News Section
    'home.news.title': 'News & Updates',
    'home.news.subtitle': 'Stay updated with the latest news about heat treatment technology and company developments',
    'home.news.readMore': 'Read More',
    'home.news.viewAll': 'View All News',
    'home.news.item1.title': 'Latest Heat Treatment Technology',
    'home.news.item1.description': 'The company has implemented the most advanced heat treatment technology to enhance work efficiency and quality',
    'home.news.item1.category': 'Technology',
    'home.news.item2.title': 'Production Capacity Expansion',
    'home.news.item2.description': 'To meet increasing demand, the company has expanded production capacity and added new machinery',
    'home.news.item2.category': 'News',
    'home.news.item3.title': 'ISO Standard Certification',
    'home.news.item3.description': 'The company received ISO 9001:2015 certification, demonstrating commitment to quality service',
    'home.news.item3.category': 'Achievement',
    'home.news.item4.title': 'Industrial Exhibition Participation',
    'home.news.item4.description': 'The company participated in industrial exhibitions to showcase new technologies and services to customers',
    'home.news.item4.category': 'Events',
    'home.news.item5.title': 'Employee Safety Training',
    'home.news.item5.description': 'Conducted safety training for employees to ensure workplace safety for everyone',
    'home.news.item5.category': 'Staff Development',
    
    // News Page
    'news.pageTitle': 'All News',
    'news.pageSubtitle': 'Stay updated with the latest news and updates from the company',
    'news.backToHome': 'Back to Home',
    'news.readMore': 'Read More',
    'news.close': 'Close',
    'news.item1.title': 'Latest Heat Treatment Technology',
    'news.item1.description': 'The company has implemented the most advanced heat treatment technology to enhance work efficiency and quality',
    'news.item1.fullContent': 'NAGATO HEAT TREATMENT (THAILAND) CO.,LTD. has implemented the most advanced heat treatment technology in the production process to enhance work efficiency and quality. This new technology will help improve temperature and time control accuracy while reducing energy consumption and increasing workplace safety.',
    'news.item1.author': 'News Team',
    'news.item2.title': 'Production Capacity Expansion',
    'news.item2.description': 'To meet increasing demand, the company has expanded production capacity and added new machinery',
    'news.item2.fullContent': 'Due to business growth and increasing demand, the company has decided to expand production capacity by adding new modern machinery and equipment, as well as expanding production areas to accommodate more customers and deliver work on time.',
    'news.item2.author': 'Production Department',
    'news.item3.title': 'ISO Standard Certification',
    'news.item3.description': 'The company received ISO 9001:2015 certification, demonstrating commitment to quality service',
    'news.item3.fullContent': 'The company received ISO 9001:2015 certification, which is an international standard for quality management systems. This certification demonstrates the company\'s commitment to providing the highest quality service and improving work system efficiency.',
    'news.item3.author': 'Quality Department',
    'news.item4.title': 'Industrial Exhibition Participation',
    'news.item4.description': 'The company participated in industrial exhibitions to showcase new technologies and services to customers',
    'news.item4.fullContent': 'The company participated in an important industrial exhibition to showcase new technologies and services to customers and business partners. This event was a great opportunity to build networks and demonstrate the company\'s capabilities in heat treatment.',
    'news.item4.author': 'Marketing Department',
    'news.item5.title': 'Employee Safety Training',
    'news.item5.description': 'Conducted safety training for employees to ensure workplace safety for everyone',
    'news.item5.fullContent': 'The company regularly conducts workplace safety training for employees to ensure everyone\'s safety and reduce the risk of accidents. The training covers both theory and practical application.',
    'news.item5.author': 'Safety Department',
    'news.item6.title': 'New R&D Center Opening',
    'news.item6.description': 'The company opened a new research and development center to develop innovations in heat treatment',
    'news.item6.fullContent': 'The company has opened a new modern research and development center to develop innovations in heat treatment and create new technologies that will help improve work efficiency and product quality.',
    'news.item6.author': 'R&D Department',
    'news.item7.title': 'University Partnership',
    'news.item7.description': 'The company partnered with universities in research and development of new innovations',
    'news.item7.fullContent': 'The company signed a cooperation agreement with leading universities in research and development of new innovations in heat treatment. This partnership will help the company access new knowledge and technologies.',
    'news.item7.author': 'Academic Department',
    'news.item8.title': 'Quality Award of the Year',
    'news.item8.description': 'The company received the Quality Award of the Year from the Industrial Association',
    'news.item8.fullContent': 'The company received the Quality Award of the Year from the Industrial Association, which is an award that demonstrates commitment to providing the highest quality service and success in sustainable business development.',
    'news.item8.author': 'Management Department',
    
    // About Page
    'about.hero.title': 'About Us',
    'about.hero.description': 'We are a company engaged in development, design, and providing all types of heat treatment services with modern technology and expert teams to enhance material quality and strength according to international standards.',
    'about.hero.technology.title': 'Modern Technology',
    'about.hero.technology.desc': 'Modern machinery and equipment controlled by digital systems',
    'about.hero.quality.title': 'High Quality',
    'about.hero.quality.desc': 'International quality standards with quality certificates',
    'about.hero.expertise.title': 'Expertise',
    'about.hero.expertise.desc': 'Expert team with extensive experience in heat treatment',
    'about.mission.title': 'Our Mission',
    'about.mission.main.title': 'Main Mission',
    'about.mission.main.desc': 'Committed to providing the highest quality heat treatment services while creating satisfaction for all customers by applying modern technology to enhance material quality.',
    'about.mission.vision.title': 'Vision',
    'about.mission.vision.desc': 'To be a leader in the heat treatment industry that customers trust through continuous development and creating new innovations to meet changing industrial needs.',
    'about.mission.values.title': 'Values',
    'about.mission.values.desc': 'Precision, responsibility, and teamwork, along with continuous self-development to provide the best heat treatment service.',
    'about.mission.commitment.title': 'Our Commitment',
    'about.mission.commitment.desc': 'We are committed to being part of driving your industry to grow sustainably by providing heat treatment services that exceed expectations and build long-term trust.',
    'about.values.title': 'Our Core Values',
    'about.values.subtitle': 'Values that we uphold and practice in all our work to build trust and satisfaction for all customers and employees.',
    'about.values.quality.title': 'Quality',
    'about.values.quality.desc': 'Committed to providing the highest quality heat treatment services in every step',
    'about.values.technology.title': 'Technology',
    'about.values.technology.desc': 'Using modern machinery and equipment controlled by digital systems',
    'about.values.precision.title': 'Precision',
    'about.values.precision.desc': 'Precise temperature and time control according to international standards',
    'about.values.reliability.title': 'Reliability',
    'about.values.reliability.desc': 'Guaranteeing quality and safety of every workpiece',
    'about.values.innovation.title': 'Innovation',
    'about.values.innovation.desc': 'Continuous development with modern technology and approaches',
    'about.values.excellence.title': 'Excellence',
    'about.values.excellence.desc': 'Striving for excellence in providing all types of heat treatment services',
    'about.values.commitment.title': 'Our Commitment',
    'about.values.commitment.desc': 'We are committed to conducting business with precision, transparency, and responsibility while continuously developing ourselves to provide the best heat treatment service to all our customers.',
    
    // Services Page
    'service.hero.title': 'Heat Treatment Services',
    'service.hero.description': 'We provide all types of heat treatment services with modern technology and expert teams to enhance material quality and strength according to international standards.',
    'service.hero.quality.title': 'High Quality',
    'service.hero.quality.desc': 'International quality standards with quality certificates',
    'service.hero.speed.title': 'Fast',
    'service.hero.speed.desc': 'On-time delivery with guaranteed quality',
    'service.hero.support.title': 'After-Sales Service',
    'service.hero.support.desc': 'Support team ready to help 24/7',

    'service.features.title': 'Heat Treatment Service Highlights',
    'service.features.subtitle': 'We provide heat treatment services with modern technology and expert teams for the best results',
    'service.features.performance.title': 'Modern Technology',
    'service.features.performance.desc': 'Modern machinery and equipment controlled by digital systems',
    'service.features.security.title': 'Security',
    'service.features.security.desc': 'Standard security system guaranteeing workpiece safety',
    'service.features.reliability.title': 'Precision',
    'service.features.reliability.desc': 'Precise temperature and time control according to international standards',
    'service.features.mobile.title': 'Comprehensive Services',
    'service.features.mobile.desc': 'Complete heat treatment services to meet the needs of various industries',
    'service.features.analytics.title': 'Quality Inspection',
    'service.features.analytics.desc': 'Inspect quality and test properties after heat treatment',
    'service.features.support.title': 'After-Sales Service',
    'service.features.support.desc': 'Support team ready to help 24/7',

    'service.process.title': 'Our Process',
    'service.process.subtitle': 'Clear, transparent, and efficient steps for the best results',
    'service.process.consultation.title': 'Consultation & Analysis',
    'service.process.consultation.desc': 'Analyze requirements and define scope of work',
    'service.process.planning.title': 'Inspection & Analysis',
    'service.process.planning.desc': 'Inspect materials and analyze properties before heat treatment',
    'service.process.development.title': 'Heat Treatment',
    'service.process.development.desc': 'Perform heat treatment according to specified standards',
    'service.process.delivery.title': 'Delivery',
    'service.process.delivery.desc': 'Deliver work with test reports and quality certificates',

    'service.pricing.title': 'Heat Treatment Service Packages',
    'service.pricing.subtitle': 'Choose a package that suits your needs or customize as needed',
    'service.pricing.basic.title': 'Basic Service',
    'service.pricing.basic.desc': 'Ideal for small-scale heat treatment',
    'service.pricing.basic.feature1': 'Annealing',
    'service.pricing.basic.feature2': 'Quenching',
    'service.pricing.basic.feature3': 'Tempering',
    'service.pricing.basic.feature4': 'Test reports',
    'service.pricing.basic.price': '$15/kg',
    'service.pricing.pro.title': 'Standard Service',
    'service.pricing.pro.desc': 'Ideal for medium-scale heat treatment',
    'service.pricing.pro.feature1': 'All Basic features',
    'service.pricing.pro.feature2': 'Normalizing',
    'service.pricing.pro.feature3': 'Carburizing',
    'service.pricing.pro.feature4': 'Nitriding',
    'service.pricing.pro.feature5': 'Quality certificates',
    'service.pricing.pro.price': '$25/kg',
    'service.pricing.enterprise.title': 'Premium Service',
    'service.pricing.enterprise.desc': 'For large-scale and specific heat treatment needs',
    'service.pricing.enterprise.feature1': 'Custom process design',
    'service.pricing.enterprise.feature2': 'Customization according to needs',
    'service.pricing.enterprise.feature3': 'End-to-end heat treatment',
    'service.pricing.enterprise.feature4': 'Training & consultation',
    'service.pricing.enterprise.feature5': 'Dedicated consultant',
    'service.pricing.enterprise.feature6': 'Quality guarantee',
    'service.pricing.enterprise.price': 'Contact us',
    'service.pricing.note': 'Prices above are indicative and may vary based on needs.',
    'service.pricing.contact': 'Contact Sales',

    'service.card.popular': 'Popular',
    'service.card.perMonth': 'per kilogram',
    'service.card.learnMore': 'Learn More',

    // Products Page
    'product.hero.title': 'Heat Treatment Services',
    'product.hero.description': 'We provide all types of heat treatment services with modern technology and expert teams to enhance material quality and strength according to international standards.',
    'product.hero.heat.title': 'Heat Technology',
    'product.hero.heat.desc': 'Precise temperature control systems',
    'product.hero.treatment.title': 'Heat Treatment',
    'product.hero.treatment.desc': 'Processes that meet international standards',
    'product.hero.quality.title': 'High Quality',
    'product.hero.quality.desc': 'Quality guaranteed for every piece',

    'product.showcase.title': 'Heat Treatment Types',
    'product.showcase.subtitle': 'Complete heat treatment services to meet the needs of various industries',
    'product.showcase.annealing.title': 'Annealing',
    'product.showcase.annealing.desc': 'Annealing process to reduce hardness and improve metal crystal structure',
    'product.showcase.annealing.feature1': 'Reduce metal hardness',
    'product.showcase.annealing.feature2': 'Improve crystal structure',
    'product.showcase.annealing.feature3': 'Increase toughness',
    'product.showcase.annealing.feature4': 'Reduce internal stress',
    'product.showcase.quenching.title': 'Quenching',
    'product.showcase.quenching.desc': 'Quenching process to increase hardness and wear resistance',
    'product.showcase.quenching.feature1': 'Maximum hardness increase',
    'product.showcase.quenching.feature2': 'Wear resistance',
    'product.showcase.quenching.feature3': 'Increase strength',
    'product.showcase.quenching.feature4': 'Improve mechanical properties',
    'product.showcase.tempering.title': 'Tempering',
    'product.showcase.tempering.desc': 'Tempering process to reduce brittleness and balance hardness with toughness',
    'product.showcase.tempering.feature1': 'Reduce brittleness',
    'product.showcase.tempering.feature2': 'Balance hardness',
    'product.showcase.tempering.feature3': 'Increase toughness',
    'product.showcase.tempering.feature4': 'Reduce internal stress',
    'product.showcase.normalizing.title': 'Normalizing',
    'product.showcase.normalizing.desc': 'Normalizing process to improve crystal structure and mechanical properties',
    'product.showcase.normalizing.feature1': 'Improve crystal structure',
    'product.showcase.normalizing.feature2': 'Increase strength',
    'product.showcase.normalizing.feature3': 'Improve mechanical properties',
    'product.showcase.normalizing.feature4': 'Reduce internal stress',
    'product.showcase.carburizing.title': 'Carburizing',
    'product.showcase.carburizing.desc': 'Carburizing process to increase surface hardness and wear resistance',
    'product.showcase.carburizing.feature1': 'Increase surface hardness',
    'product.showcase.carburizing.feature2': 'High wear resistance',
    'product.showcase.carburizing.feature3': 'Increase strength',
    'product.showcase.carburizing.feature4': 'Improve surface properties',
    'product.showcase.nitriding.title': 'Nitriding',
    'product.showcase.nitriding.desc': 'Nitriding process to increase surface hardness and corrosion resistance',
    'product.showcase.nitriding.feature1': 'High surface hardness',
    'product.showcase.nitriding.feature2': 'Corrosion resistance',
    'product.showcase.nitriding.feature3': 'Increase strength',
    'product.showcase.nitriding.feature4': 'Improve surface properties',

    'product.features.title': 'Our Highlights',
    'product.features.subtitle': 'We provide heat treatment services with modern technology and expert teams for the best results',
    'product.features.quality.title': 'High Quality',
    'product.features.quality.desc': 'International quality standards with quality certificates',
    'product.features.speed.title': 'Fast',
    'product.features.speed.desc': 'On-time delivery with guaranteed quality',
    'product.features.technology.title': 'Modern Technology',
    'product.features.technology.desc': 'Modern machinery and equipment controlled by digital systems',
    'product.features.precision.title': 'Precision',
    'product.features.precision.desc': 'Precise temperature and time control according to international standards',
    'product.features.support.title': 'After-Sales Service',
    'product.features.support.desc': 'Support team ready to help 24/7',
    'product.features.security.title': 'Security',
    'product.features.security.desc': 'Standard security system guaranteeing workpiece safety',

    'product.process.title': 'Our Process',
    'product.process.subtitle': 'Clear, transparent, and efficient steps for the best results',
    'product.process.consultation.title': 'Consultation & Analysis',
    'product.process.consultation.desc': 'Analyze requirements and define scope of work',
    'product.process.analysis.title': 'Inspection & Analysis',
    'product.process.analysis.desc': 'Inspect materials and analyze properties before heat treatment',
    'product.process.treatment.title': 'Heat Treatment',
    'product.process.treatment.desc': 'Perform heat treatment according to specified standards',
    'product.process.quality.title': 'Quality Inspection',
    'product.process.quality.desc': 'Inspect quality and test properties after heat treatment',
    'product.process.delivery.title': 'Delivery',
    'product.process.delivery.desc': 'Deliver work with test reports and quality certificates',

    'product.parts.title': 'Our Parts Gallery',
    'product.parts.subtitle': 'Explore our high-quality manufactured parts and components',
    'product.parts.overview.title': 'Parts Overview',
    'product.parts.overview.desc': 'High-quality manufactured parts',
    'product.parts.part2.title': 'Precision Part 2',
    'product.parts.part2.desc': 'Engineered with precision',
    'product.parts.part3.title': 'Advanced Part 3',
    'product.parts.part3.desc': 'Advanced manufacturing technology',

    // Contact Page
    'contact.hero.title': 'Contact Us',
    'contact.hero.description': 'We are ready to serve and answer all your questions. Contact us today for a free consultation.',
    'contact.form.title': 'Send us a Message',
    'contact.form.description': 'Fill in the information below. We will get back to you within 24 hours.',
    'contact.form.name': 'Full Name',
    'contact.form.name_placeholder': 'Enter your full name',
    'contact.form.email': 'Email',
    'contact.form.email_placeholder': 'Enter your email',
    'contact.form.phone': 'Phone Number',
    'contact.form.phone_placeholder': 'Enter your phone number',
    'contact.form.company': 'Company',
    'contact.form.company_placeholder': 'Enter your company name',
    'contact.form.subject': 'Subject',
    'contact.form.subject_placeholder': 'Select the subject you want to contact about',
    'contact.form.subject_general': 'General Inquiry',
    'contact.form.subject_support': 'Support Request',
    'contact.form.subject_sales': 'Sales Inquiry',
    'contact.form.subject_partnership': 'Partnership',
    'contact.form.subject_other': 'Other',
    'contact.form.message': 'Message',
    'contact.form.message_placeholder': 'Enter the details you want to contact about',
    'contact.form.submit': 'Send Message',
    'contact.form.submitting': 'Sending...',
    'contact.form.success': 'Message sent successfully! We will get back to you as soon as possible.',
    'contact.form.error': 'An error occurred. Please try again.',
    'contact.info.title': 'Contact Information',
    'contact.info.description': 'You can contact us through various channels. We are ready to serve and answer all your questions.',
    'contact.info.email.title': 'Email',
    'contact.info.email.description': 'Send us an email anytime, 24/7',
    'contact.info.phone.title': 'Phone',
    'contact.info.phone.description': 'Call us during business hours',
    'contact.info.address.title': 'Address',
    'contact.info.address.description': 'Visit our office',
    'contact.info.hours.title': 'Business Hours',
    'contact.info.hours.description': 'Hours when we are ready to serve',
    'contact.info.social.title': 'Follow Us',
    'contact.map.title': 'Map & Directions',
    'contact.map.description': 'Find your way to our office easily',
    'contact.map.placeholder.title': 'Map',
    'contact.map.placeholder.description': 'Map will be displayed here',
    'contact.map.placeholder.button': 'Open Map',
    'contact.map.directions.title': 'How to Get Here',
    'contact.map.directions.bts': 'BTS Asok - Exit 6',
    'contact.map.directions.mrt': 'MRT Sukhumvit - Exit 3',
    'contact.map.directions.parking': 'Building parking available',
    'contact.map.nearby.title': 'Nearby Places',
    'contact.map.nearby.terminal21': 'Terminal 21',
    'contact.map.nearby.emquartier': 'EmQuartier',
    'contact.map.nearby.benjasiri': 'Benjasiri Park',
    'contact.map.nearby.lumpini': 'Lumpini Park',
    'contact.company.name': 'NAGATO HEAT TREATMENT (THAILAND) CO.,LTD.',
    'contact.company.address.title': 'Address',
    'contact.company.phone.title': 'Phone',
    'contact.company.hours.title': 'Business Hours',
    'contact.company.address.detail': '7/379 Moo 6 Amata City Industrial Estate<br />Tambon Mab Yang Porn, Amphur Pluak Daeng<br />Rayong Province 21140',
    'contact.company.phone.detail': '038-027-473<br />062-604-1289<br /><span class="text-sky-600 font-medium">038-027-475 (Fax)</span>',
    'contact.company.hours.detail': 'Monday - Friday: 8:00 - 17:00<br />Saturday: 8:00 - 12:00<br />Sunday: Closed',
  },
  jp: {
    // NavBar
    'nav.home': 'ホーム',
    'nav.about': '会社概要',
    'nav.services': 'サービス',
    'nav.products': '製品',
    'nav.contact': 'お問い合わせ',
    'nav.business_hours': '営業時間: 月-金 8:00-17:00',
    'nav.phone': '038-027-473',
    'nav.email': 'info@nagato.co.th',
    
    // Footer
    'footer.company_description': '当社は、プロフェッショナルなチームと最新技術で最高品質のサービスを提供することにコミットしています。',
    'footer.quick_links': 'クイックリンク',
    'footer.contact_us': 'お問い合わせ',
    'footer.location': '所在地',
    'footer.address_line1': '7/379 ムー6 アマタシティ工業団地',
    'footer.address_line2': 'タンボン・マブヤンプーン、アムプル・プルアクダエン',
    'footer.address_line3': 'ラヨーン県 21140',
    'footer.copyright': 'あなたの会社株式会社。全著作権所有。',
    'footer.privacy': 'プライバシーポリシー',
    'footer.terms': '利用規約',
    'footer.phone': '038-027-473, 062-604-1289',
    'footer.fax': '038-027-475',
    
    // Meta
    'meta.title': 'あなたの会社 - 高品質サービス',
    'meta.description': '当社は、プロフェッショナルなチームと最新技術で最高品質のサービスを提供することにコミットしています。',
    
    // Home Page
    'home.hero.title': 'ようこそ',
    'home.hero.subtitle': 'NAGATO HEAT TREATMENT (THAILAND) CO.,LTD.',
    'home.hero.description': '最新技術と専門チームで、国際基準に準拠した材料の品質と強度を向上させるあらゆるタイプの熱処理サービスを提供します。',
    'home.hero.cta1': '始める',
    'home.hero.cta2': '詳細を見る',
    'home.features.title': 'なぜ私たちを選ぶのか',
    'home.features.subtitle': '最新技術と専門チームで最高の熱処理サービスを提供することにコミットしています。',
    'home.features.technology.title': '最新技術',
    'home.features.technology.desc': '最大の精密性のためにデジタルシステムで制御される最新の機械と設備。',
    'home.features.quality.title': '高品質',
    'home.features.quality.desc': '品質証明書付きの国際品質基準、期待を超える結果を保証。',
    'home.features.precision.title': '精密性',
    'home.features.precision.desc': '国際基準に準拠した精密な温度と時間制御で一貫した結果を実現。',
    'home.features.reliability.title': '信頼性',
    'home.features.reliability.desc': '厳格な品質検査システムで、すべてのワークピースの品質と安全性を保証。',
    'home.features.innovation.title': 'イノベーション',
    'home.features.innovation.desc': '変化するニーズに応えるための最新技術とアプローチによる継続的な開発。',
    'home.features.support.title': 'アフターサービス',
    'home.features.support.desc': 'コンサルティングと問題解決で24時間体制でサポートするサポートチーム。',
    'home.about.title': '会社概要',
    'home.about.desc1': 'Nagatoは、開発、設計、そして最新技術と専門チームで国際基準に準拠した材料の品質と強度を向上させるあらゆるタイプの熱処理サービスを提供する会社です。',
    'home.about.desc2': '最高の熱処理サービスを提供するというコミットメントにより、全国の顧客からの信頼を得ており、お客様の産業を成功に導く一員となる準備ができています。',
    'home.about.cta': '詳細を見る',
    'home.about.stats.customers': '信頼できる顧客',
    'home.about.stats.quality': '品質保証',
    'home.about.stats.support': 'サポートサービス',
    'home.about.stats.experience': '年の経験',
    'home.cta.title': '始める準備はできましたか？',
    'home.cta.description': '私たちに参加して、プロフェッショナルなチームからのサポートで最高の熱処理サービスを体験してください。',
    'home.cta.button1': '無料で始める',
    'home.cta.button2': 'お問い合わせ',
    'home.cta.trust': '主要企業に信頼されています',
    'home.cta.trust1': '自動車産業',
    'home.cta.trust2': '機械産業',
    'home.cta.trust3': '航空宇宙産業',
    'home.cta.trust4': 'エネルギー産業',
    
    // News Section
    'home.news.title': 'ニュース・アップデート',
    'home.news.subtitle': '熱処理技術と会社の発展に関する最新ニュースをお知らせします',
    'home.news.readMore': '続きを読む',
    'home.news.viewAll': 'すべてのニュースを見る',
    'home.news.item1.title': '最新の熱処理技術',
    'home.news.item1.description': '会社は作業効率と品質を向上させるために最も先進的な熱処理技術を導入しました',
    'home.news.item1.category': '技術',
    'home.news.item2.title': '生産能力の拡大',
    'home.news.item2.description': '需要の増加に対応するため、会社は生産能力を拡大し、新しい機械を追加しました',
    'home.news.item2.category': 'ニュース',
    'home.news.item3.title': 'ISO標準認証取得',
    'home.news.item3.description': '会社はISO 9001:2015認証を取得し、品質サービスへの取り組みを示しています',
    'home.news.item3.category': '成果',
    'home.news.item4.title': '産業展示会への参加',
    'home.news.item4.description': '会社は産業展示会に参加し、お客様に新しい技術とサービスを紹介しました',
    'home.news.item4.category': 'イベント',
    'home.news.item5.title': '従業員安全研修',
    'home.news.item5.description': '全員の職場安全を確保するため、従業員向けの安全研修を実施しました',
    'home.news.item5.category': '人材開発',
    
    // News Page
    'news.pageTitle': 'すべてのニュース',
    'news.pageSubtitle': '会社からの最新ニュースとアップデートをお知らせします',
    'news.backToHome': 'ホームに戻る',
    'news.readMore': '続きを読む',
    'news.close': '閉じる',
    'news.item1.title': '最新の熱処理技術',
    'news.item1.description': '会社は作業効率と品質を向上させるために最も先進的な熱処理技術を導入しました',
    'news.item1.fullContent': 'NAGATO HEAT TREATMENT (THAILAND) CO.,LTD.は、作業効率と品質を向上させるために、生産プロセスに最も先進的な熱処理技術を導入しました。この新しい技術により、温度と時間の制御精度が向上し、エネルギー消費を削減し、職場の安全性を高めることができます。',
    'news.item1.author': 'ニュースチーム',
    'news.item2.title': '生産能力の拡大',
    'news.item2.description': '需要の増加に対応するため、会社は生産能力を拡大し、新しい機械を追加しました',
    'news.item2.fullContent': 'ビジネスの成長と需要の増加により、会社は新しい現代的な機械と設備を追加し、生産エリアを拡大することで生産能力を拡大することを決定しました。これにより、より多くの顧客に対応し、時間通りに作業を納品できるようになります。',
    'news.item2.author': '生産部門',
    'news.item3.title': 'ISO標準認証取得',
    'news.item3.description': '会社はISO 9001:2015認証を取得し、品質サービスへの取り組みを示しています',
    'news.item3.fullContent': '会社は品質管理システムの国際標準であるISO 9001:2015認証を取得しました。この認証は、最高品質のサービスを提供し、作業システムの効率を向上させるという会社の取り組みを示しています。',
    'news.item3.author': '品質部門',
    'news.item4.title': '産業展示会への参加',
    'news.item4.description': '会社は産業展示会に参加し、お客様に新しい技術とサービスを紹介しました',
    'news.item4.fullContent': '会社は重要な産業展示会に参加し、お客様やビジネスパートナーに新しい技術とサービスを紹介しました。このイベントは、ネットワークを構築し、熱処理における会社の能力を実証する素晴らしい機会でした。',
    'news.item4.author': 'マーケティング部門',
    'news.item5.title': '従業員安全研修',
    'news.item5.description': '全員の職場安全を確保するため、従業員向けの安全研修を実施しました',
    'news.item5.fullContent': '会社は従業員の職場安全研修を定期的に実施し、全員の安全を確保し、事故のリスクを軽減しています。研修は理論と実践の両方をカバーしています。',
    'news.item5.author': '安全部門',
    'news.item6.title': '新R&Dセンター開設',
    'news.item6.description': '会社は熱処理のイノベーション開発のため、新しい研究開発センターを開設しました',
    'news.item6.fullContent': '会社は熱処理のイノベーション開発と、作業効率と製品品質の向上に役立つ新しい技術の創造のため、新しい現代的な研究開発センターを開設しました。',
    'news.item6.author': 'R&D部門',
    'news.item7.title': '大学とのパートナーシップ',
    'news.item7.description': '会社は大学と新しいイノベーションの研究開発で協力しました',
    'news.item7.fullContent': '会社は熱処理における新しいイノベーションの研究開発で主要大学と協力協定を締結しました。このパートナーシップにより、会社は新しい知識と技術にアクセスできるようになります。',
    'news.item7.author': '学術部門',
    'news.item8.title': '年間品質賞受賞',
    'news.item8.description': '会社は産業協会から年間品質賞を受賞しました',
    'news.item8.fullContent': '会社は産業協会から年間品質賞を受賞しました。これは、最高品質のサービスを提供するという取り組みと持続可能なビジネス開発の成功を示す賞です。',
    'news.item8.author': '管理部門',
    
    // About Page
    'about.hero.title': '会社概要',
    'about.hero.description': '私たちは、開発、設計、そして最新技術と専門チームで国際基準に準拠した材料の品質と強度を向上させるあらゆるタイプの熱処理サービスを提供する会社です。',
    'about.hero.technology.title': '最新技術',
    'about.hero.technology.desc': 'デジタルシステムで制御される最新の機械と設備',
    'about.hero.quality.title': '高品質',
    'about.hero.quality.desc': '品質証明書付きの国際品質基準',
    'about.hero.expertise.title': '専門知識',
    'about.hero.expertise.desc': '熱処理分野で豊富な経験を持つ専門チーム',
    'about.mission.title': '私たちのミッション',
    'about.mission.main.title': '主要ミッション',
    'about.mission.main.desc': '最新技術を適用して材料の品質を向上させながら、すべてのお客様に満足を提供する最高品質の熱処理サービスを提供することにコミットしています。',
    'about.mission.vision.title': 'ビジョン',
    'about.mission.vision.desc': '継続的な開発と変化する産業ニーズに応える新しいイノベーションの創造を通じて、お客様に信頼される熱処理業界のリーダーになること。',
    'about.mission.values.title': '価値観',
    'about.mission.values.desc': '精密性、責任感、チームワーク、そして最高の熱処理サービスを提供するための継続的な自己開発。',
    'about.mission.commitment.title': '私たちのコミットメント',
    'about.mission.commitment.desc': '期待を超える熱処理サービスを提供し、長期的な信頼を築くことで、お客様の産業を持続可能に成長させる一員となることにコミットしています。',
    'about.values.title': '私たちのコアバリュー',
    'about.values.subtitle': 'すべてのお客様と従業員の信頼と満足を築くために、すべての仕事で守り実践する価値観。',
    'about.values.quality.title': '品質',
    'about.values.quality.desc': 'すべてのステップで最高品質の熱処理サービスを提供することにコミット',
    'about.values.technology.title': '技術',
    'about.values.technology.desc': 'デジタルシステムで制御される最新の機械と設備の使用',
    'about.values.precision.title': '精密性',
    'about.values.precision.desc': '国際基準に準拠した精密な温度と時間制御',
    'about.values.reliability.title': '信頼性',
    'about.values.reliability.desc': 'すべてのワークピースの品質と安全性を保証',
    'about.values.innovation.title': 'イノベーション',
    'about.values.innovation.desc': '最新技術と現代的なアプローチによる継続的な開発',
    'about.values.excellence.title': '卓越性',
    'about.values.excellence.desc': 'あらゆるタイプの熱処理サービスの提供における卓越性の追求',
    'about.values.commitment.title': '私たちのコミットメント',
    'about.values.commitment.desc': '私たちは、精密性、透明性、責任感を持ってビジネスを運営し、すべてのお客様に最高の熱処理サービスを提供するために継続的に自己開発することにコミットしています。',
    
    // Services Page
    'service.hero.title': '熱処理サービス',
    'service.hero.description': '最新技術と専門チームで、国際基準に準拠した材料の品質と強度を向上させるあらゆるタイプの熱処理サービスを提供します。',
    'service.hero.quality.title': '高品質',
    'service.hero.quality.desc': '品質証明書付きの国際品質基準',
    'service.hero.speed.title': '高速',
    'service.hero.speed.desc': '品質保証付きの時間通りの納品',
    'service.hero.support.title': 'アフターサービス',
    'service.hero.support.desc': '24時間体制でサポートするサポートチーム',

    'service.features.title': '熱処理サービスの特徴',
    'service.features.subtitle': '最新技術と専門チームで最高の結果を得るための熱処理サービスを提供',
    'service.features.performance.title': '最新技術',
    'service.features.performance.desc': 'デジタルシステムで制御される最新の機械と設備',
    'service.features.security.title': 'セキュリティ',
    'service.features.security.desc': 'ワークピースの安全性を保証する標準セキュリティシステム',
    'service.features.reliability.title': '精密性',
    'service.features.reliability.desc': '国際基準に準拠した精密な温度と時間制御',
    'service.features.mobile.title': '包括的サービス',
    'service.features.mobile.desc': '様々な産業のニーズに応える完全な熱処理サービス',
    'service.features.analytics.title': '品質検査',
    'service.features.analytics.desc': '熱処理後の品質を検査し、特性をテスト',
    'service.features.support.title': 'アフターサービス',
    'service.features.support.desc': '24時間体制でサポートするサポートチーム',

    'service.process.title': '私たちのプロセス',
    'service.process.subtitle': '最高の結果のための明確で透明性があり効率的なステップ',
    'service.process.consultation.title': '相談・分析',
    'service.process.consultation.desc': '要件を分析し、作業範囲を定義',
    'service.process.planning.title': '検査・分析',
    'service.process.planning.desc': '熱処理前に材料を検査し、特性を分析',
    'service.process.development.title': '熱処理',
    'service.process.development.desc': '指定された基準に従って熱処理を実行',
    'service.process.delivery.title': '納品',
    'service.process.delivery.desc': 'テストレポートと品質証明書付きで作業を納品',

    'service.pricing.title': '熱処理サービスプラン',
    'service.pricing.subtitle': 'ニーズに合うプランを選ぶか、必要に応じてカスタマイズ',
    'service.pricing.basic.title': '基本サービス',
    'service.pricing.basic.desc': '小規模熱処理に最適',
    'service.pricing.basic.feature1': '焼きなまし',
    'service.pricing.basic.feature2': '焼入れ',
    'service.pricing.basic.feature3': '焼戻し',
    'service.pricing.basic.feature4': 'テストレポート',
    'service.pricing.basic.price': '¥2,200/kg',
    'service.pricing.pro.title': '標準サービス',
    'service.pricing.pro.desc': '中規模熱処理に最適',
    'service.pricing.pro.feature1': '基本の全機能',
    'service.pricing.pro.feature2': '焼ならし',
    'service.pricing.pro.feature3': '浸炭',
    'service.pricing.pro.feature4': '窒化',
    'service.pricing.pro.feature5': '品質証明書',
    'service.pricing.pro.price': '¥3,500/kg',
    'service.pricing.enterprise.title': 'プレミアムサービス',
    'service.pricing.enterprise.desc': '大規模かつ特定の熱処理ニーズに対応',
    'service.pricing.enterprise.feature1': 'カスタムプロセス設計',
    'service.pricing.enterprise.feature2': 'ニーズに応じたカスタマイズ',
    'service.pricing.enterprise.feature3': 'エンドツーエンド熱処理',
    'service.pricing.enterprise.feature4': 'トレーニングとコンサルティング',
    'service.pricing.enterprise.feature5': '専任コンサルタント',
    'service.pricing.enterprise.feature6': '品質保証',
    'service.pricing.enterprise.price': 'お問い合わせ',
    'service.pricing.note': '上記の価格は目安であり、要件により変動します。',
    'service.pricing.contact': '営業に問い合わせる',

    'service.card.popular': '人気',
    'service.card.perMonth': 'キログラムあたり',
    'service.card.learnMore': '詳しく見る',

    // Products Page
    'product.hero.title': '熱処理サービス',
    'product.hero.description': '最新技術と専門チームで、国際基準に準拠した材料の品質と強度を向上させるあらゆるタイプの熱処理サービスを提供します。',
    'product.hero.heat.title': '熱技術',
    'product.hero.heat.desc': '精密な温度制御システム',
    'product.hero.treatment.title': '熱処理',
    'product.hero.treatment.desc': '国際基準を満たすプロセス',
    'product.hero.quality.title': '高品質',
    'product.hero.quality.desc': 'すべての部品の品質保証',

    'product.showcase.title': '熱処理の種類',
    'product.showcase.subtitle': '様々な産業のニーズに応える完全な熱処理サービス',
    'product.showcase.annealing.title': '焼きなまし',
    'product.showcase.annealing.desc': '硬度を下げ、金属の結晶構造を改善する焼きなましプロセス',
    'product.showcase.annealing.feature1': '金属の硬度を下げる',
    'product.showcase.annealing.feature2': '結晶構造を改善',
    'product.showcase.annealing.feature3': '靭性を向上',
    'product.showcase.annealing.feature4': '内部応力を軽減',
    'product.showcase.quenching.title': '焼入れ',
    'product.showcase.quenching.desc': '硬度と耐摩耗性を向上させる焼入れプロセス',
    'product.showcase.quenching.feature1': '最大硬度向上',
    'product.showcase.quenching.feature2': '耐摩耗性',
    'product.showcase.quenching.feature3': '強度向上',
    'product.showcase.quenching.feature4': '機械的特性改善',
    'product.showcase.tempering.title': '焼戻し',
    'product.showcase.tempering.desc': '脆性を減らし、硬度と靭性のバランスを取る焼戻しプロセス',
    'product.showcase.tempering.feature1': '脆性を減らす',
    'product.showcase.tempering.feature2': '硬度のバランス',
    'product.showcase.tempering.feature3': '靭性向上',
    'product.showcase.tempering.feature4': '内部応力軽減',
    'product.showcase.normalizing.title': '焼ならし',
    'product.showcase.normalizing.desc': '結晶構造と機械的特性を改善する焼ならしプロセス',
    'product.showcase.normalizing.feature1': '結晶構造改善',
    'product.showcase.normalizing.feature2': '強度向上',
    'product.showcase.normalizing.feature3': '機械的特性改善',
    'product.showcase.normalizing.feature4': '内部応力軽減',
    'product.showcase.carburizing.title': '浸炭',
    'product.showcase.carburizing.desc': '表面硬度と耐摩耗性を向上させる浸炭プロセス',
    'product.showcase.carburizing.feature1': '表面硬度向上',
    'product.showcase.carburizing.feature2': '高耐摩耗性',
    'product.showcase.carburizing.feature3': '強度向上',
    'product.showcase.carburizing.feature4': '表面特性改善',
    'product.showcase.nitriding.title': '窒化',
    'product.showcase.nitriding.desc': '表面硬度と耐食性を向上させる窒化プロセス',
    'product.showcase.nitriding.feature1': '高表面硬度',
    'product.showcase.nitriding.feature2': '耐食性',
    'product.showcase.nitriding.feature3': '強度向上',
    'product.showcase.nitriding.feature4': '表面特性改善',

    'product.features.title': '私たちの特徴',
    'product.features.subtitle': '最新技術と専門チームで最高の結果を得るための熱処理サービスを提供',
    'product.features.quality.title': '高品質',
    'product.features.quality.desc': '品質証明書付きの国際品質基準',
    'product.features.speed.title': '高速',
    'product.features.speed.desc': '品質保証付きの時間通りの納品',
    'product.features.technology.title': '最新技術',
    'product.features.technology.desc': 'デジタルシステムで制御される最新の機械と設備',
    'product.features.precision.title': '精密性',
    'product.features.precision.desc': '国際基準に準拠した精密な温度と時間制御',
    'product.features.support.title': 'アフターサービス',
    'product.features.support.desc': '24時間体制でサポートするサポートチーム',
    'product.features.security.title': 'セキュリティ',
    'product.features.security.desc': 'ワークピースの安全性を保証する標準セキュリティシステム',

    'product.process.title': '私たちのプロセス',
    'product.process.subtitle': '最高の結果のための明確で透明性があり効率的なステップ',
    'product.process.consultation.title': '相談・分析',
    'product.process.consultation.desc': '要件を分析し、作業範囲を定義',
    'product.process.analysis.title': '検査・分析',
    'product.process.analysis.desc': '熱処理前に材料を検査し、特性を分析',
    'product.process.treatment.title': '熱処理',
    'product.process.treatment.desc': '指定された基準に従って熱処理を実行',
    'product.process.quality.title': '品質検査',
    'product.process.quality.desc': '熱処理後の品質を検査し、特性をテスト',
    'product.process.delivery.title': '納品',
    'product.process.delivery.desc': 'テストレポートと品質証明書付きで作業を納品',

    'product.parts.title': '私たちの部品ギャラリー',
    'product.parts.subtitle': '高品質で製造された部品とコンポーネントをご覧ください',
    'product.parts.overview.title': '部品概要',
    'product.parts.overview.desc': '高品質で製造された部品',
    'product.parts.part2.title': '精密部品 2',
    'product.parts.part2.desc': '精密に設計・製造',
    'product.parts.part3.title': '高度な部品 3',
    'product.parts.part3.desc': '高度な製造技術',

    // Contact Page
    'contact.hero.title': 'お問い合わせ',
    'contact.hero.description': 'お客様のご質問にお答えし、サービスを提供する準備ができています。無料相談は今すぐお問い合わせください。',
    'contact.form.title': 'メッセージを送信',
    'contact.form.description': '以下の情報を入力してください。24時間以内にご連絡いたします。',
    'contact.form.name': 'お名前',
    'contact.form.name_placeholder': 'お名前を入力してください',
    'contact.form.email': 'メールアドレス',
    'contact.form.email_placeholder': 'メールアドレスを入力してください',
    'contact.form.phone': '電話番号',
    'contact.form.phone_placeholder': '電話番号を入力してください',
    'contact.form.company': '会社名',
    'contact.form.company_placeholder': '会社名を入力してください',
    'contact.form.subject': '件名',
    'contact.form.subject_placeholder': 'お問い合わせの件名を選択してください',
    'contact.form.subject_general': '一般的なお問い合わせ',
    'contact.form.subject_support': 'サポート依頼',
    'contact.form.subject_sales': '営業お問い合わせ',
    'contact.form.subject_partnership': 'パートナーシップ',
    'contact.form.subject_other': 'その他',
    'contact.form.message': 'メッセージ',
    'contact.form.message_placeholder': 'お問い合わせの詳細を入力してください',
    'contact.form.submit': 'メッセージを送信',
    'contact.form.submitting': '送信中...',
    'contact.form.success': 'メッセージが正常に送信されました！できるだけ早くご連絡いたします。',
    'contact.form.error': 'エラーが発生しました。もう一度お試しください。',
    'contact.info.title': 'お問い合わせ情報',
    'contact.info.description': '様々なチャネルでお問い合わせいただけます。お客様のご質問にお答えし、サービスを提供する準備ができています。',
    'contact.info.email.title': 'メール',
    'contact.info.email.description': '24時間いつでもメールをお送りください',
    'contact.info.phone.title': '電話',
    'contact.info.phone.description': '営業時間内にお電話ください',
    'contact.info.address.title': '住所',
    'contact.info.address.description': 'オフィスにお越しください',
    'contact.info.hours.title': '営業時間',
    'contact.info.hours.description': 'サービス提供時間',
    'contact.info.social.title': 'フォローする',
    'contact.map.title': '地図とアクセス',
    'contact.map.description': 'オフィスへの道のりを簡単に見つけることができます',
    'contact.map.placeholder.title': '地図',
    'contact.map.placeholder.description': '地図がここに表示されます',
    'contact.map.placeholder.button': '地図を開く',
    'contact.map.directions.title': 'アクセス方法',
    'contact.map.directions.bts': 'BTSアソーク - 6番出口',
    'contact.map.directions.mrt': 'MRTスクンビット - 3番出口',
    'contact.map.directions.parking': '建物内駐車場あり',
    'contact.map.nearby.title': '周辺施設',
    'contact.map.nearby.terminal21': 'ターミナル21',
    'contact.map.nearby.emquartier': 'エムクォーティア',
    'contact.map.nearby.benjasiri': 'ベンチャシリ公園',
    'contact.map.nearby.lumpini': 'ルンピニ公園',
    'contact.company.name': 'NAGATO HEAT TREATMENT (THAILAND) CO.,LTD.',
    'contact.company.address.title': '住所',
    'contact.company.phone.title': '電話',
    'contact.company.hours.title': '営業時間',
    'contact.company.address.detail': '7/379 ムー6 アマタシティ工業団地<br />タンボン・マブヤンプーン、アムプル・プルアクダエン<br />ラヨーン県 21140',
    'contact.company.phone.detail': '038-027-473<br />062-604-1289<br /><span class="text-sky-600 font-medium">038-027-475 (ファックス)</span>',
    'contact.company.hours.detail': '月曜日 - 金曜日: 8:00 - 17:00<br />土曜日: 8:00 - 12:00<br />日曜日: 休業',
  },
};

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
