'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { useSearchParams } from 'next/navigation';

export type Language = 'th' | 'en' | 'jp' | 'cn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation data
const translations = {
  th: {
    // NavBar
    'nav.home': 'หน้าแรก',
    'nav.about': 'เกี่ยวกับเรา',
    'nav.services': 'บริการ',
    'nav.products': 'ผลิตภัณฑ์',
    'nav.inspection': 'ศูนย์ตรวจสอบ',
    'nav.contact': 'ติดต่อเรา',
    'nav.business_hours': 'เปิดบริการ: จันทร์-ศุกร์ 07:30-16:30',
    'nav.phone': '038-027-473-4',
    'nav.email': 'info@nagato.co.th',
    
    // Inspection Facility
    'inspection.title': 'ตรวจสอบชิ้นงานตามข้อกำหนดของลูกค้า',
    'inspection.description': 'ระบบตรวจสอบและทดสอบชิ้นงานด้วยเครื่องมือที่ทันสมัย เพื่อให้มั่นใจในคุณภาพและมาตรฐานตามข้อกำหนดของลูกค้า',
    'inspection.equipment.magnetic.title': 'Magnetic Particle Testing Machine',
    'inspection.equipment.magnetic.spec': 'ตรวจสอบชิ้นงานตามข้อกำหนดของลูกค้า',
    'inspection.equipment.rockwell.title': 'ROCKWELL TYPE HARDNESS TESTER',
    'inspection.equipment.rockwell.spec': 'FUTURE-TECH FR-1AN',
    'inspection.equipment.vickers.title': 'VICKERS HARDNESS TESTER',
    'inspection.equipment.vickers.spec': 'FUTURE-TECH FM-300e',
    'inspection.equipment.micro.title': 'MICRO-VICKERS HARDNESS TESTER',
    'inspection.equipment.micro.spec': 'FUTURE-TECH FM-300',
    'inspection.equipment.microscope.title': 'INVERTED METALLURGICAL MICROSCOPES',
    'inspection.equipment.microscope.spec': 'OLYMPUS GX51 Expand X 1000',
    'inspection.equipment.units': '1 หน่วย',
    'inspection.equipment.specifications': 'รายละเอียด',
    'inspection.equipment.available': 'จำนวน',
    
    // Footer
    'footer.company_description': 'NAGATO HEAT TREATMENT (THAILAND) CO., LTD.',
    'footer.quick_links': 'ลิงก์ด่วน',
    'footer.contact_us': 'ติดต่อเรา',
    'footer.location': 'ที่ตั้ง',
    'footer.address_line1': '7/379 หมู่ที่ 6 นิคมอุตสาหกรรมอมตะซิตี้',
    'footer.address_line2': 'ตำบลมาบยางพร อำเภอปลวกแดง',
    'footer.address_line3': 'จังหวัดระยอง 21140',
    'footer.copyright': 'NAGATO HEAT TREATMENT (THAILAND) CO., LTD. All rights reserved.',
    'footer.privacy': 'นโยบายความเป็นส่วนตัว',
    'footer.terms': 'ข้อกำหนดการใช้งาน',
    'footer.phone': '038-027-473-4',
    'footer.fax': '038-027-473-4',
    
    // Meta
    'meta.title': 'บริษัทของคุณ - บริการคุณภาพสูง',
    'meta.description': 'บริษัทของเรามุ่งมั่นในการให้บริการที่มีคุณภาพสูงสุด พร้อมด้วยทีมงานมืออาชีพและเทคโนโลยีที่ทันสมัย',
    
    // Home Page
    'home.hero.title': '',
    'home.hero.subtitle': 'บริษัท นากาโตะ ฮีท ทรีทเม้นท์ จำกัด',
    'home.hero.description': 'มุ่งมั่นผลิตสินค้าด้วยความจริงใจ เพื่อสร้างความพึงพอใจให้กับลูกค้า\nปรับปรุงอย่างต่อเนื่อง เพื่อส่งมอบคุณภาพและการบริการที่ดีให้กับลูกค้า',
    'home.hero.cta1': 'เริ่มต้นใช้งาน',
    'home.hero.cta2': 'เรียนรู้เพิ่มเติม',
    'home.hero.scroll': 'เลื่อน',
    'home.features.title': 'ทำไมต้องเลือกเรา',
    'home.features.subtitle': 'เรามุ่งมั่นให้บริการอบ ชุบ ที่ดีที่สุด ด้วยเทคโนโลยีที่ทันสมัยและทีมงานผู้เชี่ยวชาญ',
    'home.features.technology.title': 'เทคโนโลยีทันสมัย',
    'home.features.technology.desc': 'เครื่องจักรและอุปกรณ์ที่ทันสมัย ควบคุมด้วยระบบดิจิทัล เพื่อความแม่นยำสูงสุด',
    'home.features.quality.title': 'คุณภาพสูง',
    'home.features.quality.desc': 'มาตรฐานคุณภาพระดับสากล พร้อมใบรับรองคุณภาพ รับประกันผลลัพธ์ที่เหนือความคาดหวัง',
    'home.features.precision.title': 'ความแม่นยำ',
    'home.features.precision.desc': 'ควบคุมอุณหภูมิและเวลาอย่างแม่นยำ ตามมาตรฐานสากล เพื่อผลลัพธ์ที่สม่ำเสมอ',
    'home.features.reliability.title': 'ความน่าเชื่อถือ',
    'home.features.reliability.desc': 'รับประกันคุณภาพและความปลอดภัยของชิ้นงานทุกชิ้น ด้วยระบบตรวจสอบคุณภาพที่เข้มงวด',
    'home.features.innovation.title': 'นวัตกรรม',
    'home.features.innovation.desc': 'พัฒนาอย่างต่อเนื่องด้วยเทคโนโลยีและแนวทางที่ทันสมัย เพื่อตอบสนองความต้องการที่เปลี่ยนแปลงไป',
    'home.features.support.title': 'บริการหลังการขาย',
    'home.features.support.desc': 'ทีมสนับสนุนที่พร้อมช่วยเหลือคุณตลอด 24 ชั่วโมง พร้อมให้คำปรึกษาและแก้ไขปัญหา',
    'home.about.title': 'เกี่ยวกับเรา',
    'home.about.desc1': 'Nagato เป็นบริษัทที่ประกอบกิจการพัฒนา ออกแบบ และให้บริการอบ ชุบ (Heat Treatment) ทุกประเภท ด้วยเทคโนโลยีที่ทันสมัยและทีมงานผู้เชี่ยวชาญ เพื่อเพิ่มคุณภาพและความแข็งแกร่งของวัสดุให้ตรงตามมาตรฐานสากล',
    'home.about.desc2': 'ด้วยความมุ่งมั่นในการให้บริการอบ ชุบ ที่ดีที่สุด เราจึงได้รับความไว้วางใจจากลูกค้าทั่วประเทศ และพร้อมที่จะเป็นส่วนหนึ่งในการขับเคลื่อนอุตสาหกรรมของคุณไปสู่ความสำเร็จ',
    'home.about.cta': 'เรียนรู้เพิ่มเติม',
    'home.about.stats.customers': 'ลูกค้าที่ไว้วางใจ',
    'home.about.stats.quality': 'คุณภาพรับประกัน',
    'home.about.stats.support': 'บริการสนับสนุน',
    'home.about.stats.experience': 'ปีประสบการณ์',
    'home.cta.title': 'พร้อมเริ่มต้นแล้วหรือยัง?',
    'home.cta.description': 'เข้าร่วมกับเราและสัมผัสประสบการณ์การอบ ชุบ ที่ดีที่สุด พร้อมรับการสนับสนุนจากทีมงานมืออาชีพ',
    'home.cta.button1': 'เริ่มใช้งานฟรี',
    'home.cta.button2': 'ติดต่อเรา',
    'home.cta.trust': 'เชื่อถือโดยบริษัทชั้นนำ',
    'home.cta.trust1': 'อุตสาหกรรมยานยนต์',
    'home.cta.trust2': 'อุตสาหกรรมเครื่องจักร',
    'home.cta.trust3': 'อุตสาหกรรมอากาศยาน',
    'home.cta.trust4': 'อุตสาหกรรมพลังงาน',
    
    // News Section
    'home.news.title': 'ข่าวสารและอัพเดท',
    'home.news.subtitle': 'ติดตามข่าวสารล่าสุดเกี่ยวกับเทคโนโลยีการอบ ชุบ และการพัฒนาของบริษัท',
    'home.news.readMore': 'อ่านเพิ่มเติม',
    'home.news.viewAll': 'ดูข่าวสารทั้งหมด',
    'home.news.item1.title': 'เทคโนโลยีการอบ ชุบ ใหม่ล่าสุด',
    'home.news.item1.description': 'บริษัทได้นำเทคโนโลยีการอบ ชุบ ที่ทันสมัยที่สุดมาใช้ เพื่อเพิ่มประสิทธิภาพและคุณภาพของงานให้สูงขึ้น',
    'home.news.item1.category': 'เทคโนโลยี',
    'home.news.item2.title': 'ขยายกำลังการผลิต',
    'home.news.item2.description': 'เพื่อตอบสนองความต้องการที่เพิ่มขึ้น บริษัทได้ขยายกำลังการผลิตและเพิ่มเครื่องจักรใหม่',
    'home.news.item2.category': 'ข่าวสาร',
    'home.news.item3.title': 'รับใบรับรองมาตรฐาน ISO',
    'home.news.item3.description': 'บริษัทได้รับใบรับรองมาตรฐาน ISO 9001:2015 ซึ่งแสดงถึงความมุ่งมั่นในการให้บริการที่มีคุณภาพ',
    'home.news.item3.category': 'ความสำเร็จ',
    'home.news.item4.title': 'ร่วมงานแสดงสินค้าอุตสาหกรรม',
    'home.news.item4.description': 'บริษัทเข้าร่วมงานแสดงสินค้าอุตสาหกรรมเพื่อนำเสนอเทคโนโลยีและบริการใหม่ๆ ให้กับลูกค้า',
    'home.news.item4.category': 'กิจกรรม',
    'home.news.item5.title': 'อบรมพนักงานด้านความปลอดภัย',
    'home.news.item5.description': 'จัดอบรมพนักงานด้านความปลอดภัยในการทำงาน เพื่อให้มั่นใจในความปลอดภัยของทุกคน',
    'home.news.item5.category': 'การพัฒนาบุคลากร',
    
    // News Page
    'news.pageTitle': 'ข่าวสารทั้งหมด',
    'news.pageSubtitle': 'ติดตามข่าวสารและอัพเดทล่าสุดจากบริษัท',
    'news.backToHome': 'กลับไปหน้าแรก',
    'news.readMore': 'อ่านเพิ่มเติม',
    'news.close': 'ปิด',
    'news.item1.title': 'เทคโนโลยีการอบ ชุบ ใหม่ล่าสุด',
    'news.item1.description': 'บริษัทได้นำเทคโนโลยีการอบ ชุบ ที่ทันสมัยที่สุดมาใช้ เพื่อเพิ่มประสิทธิภาพและคุณภาพของงานให้สูงขึ้น',
    'news.item1.fullContent': 'บริษัท NAGATO HEAT TREATMENT (THAILAND) CO.,LTD. ได้นำเทคโนโลยีการอบ ชุบ ที่ทันสมัยที่สุดมาใช้ในกระบวนการผลิต เพื่อเพิ่มประสิทธิภาพและคุณภาพของงานให้สูงขึ้น โดยเทคโนโลยีใหม่นี้จะช่วยให้การควบคุมอุณหภูมิและเวลามีความแม่นยำมากขึ้น พร้อมทั้งลดการใช้พลังงานและเพิ่มความปลอดภัยในการทำงาน',
    'news.item1.author': 'ทีมข่าวสาร',
    'news.item2.title': 'ขยายกำลังการผลิต',
    'news.item2.description': 'เพื่อตอบสนองความต้องการที่เพิ่มขึ้น บริษัทได้ขยายกำลังการผลิตและเพิ่มเครื่องจักรใหม่',
    'news.item2.fullContent': 'เนื่องจากการเติบโตของธุรกิจและความต้องการที่เพิ่มขึ้น บริษัทได้ตัดสินใจขยายกำลังการผลิตโดยการเพิ่มเครื่องจักรและอุปกรณ์ใหม่ที่ทันสมัย พร้อมทั้งขยายพื้นที่การผลิต เพื่อให้สามารถรองรับลูกค้าได้มากขึ้นและส่งมอบงานได้ตรงตามกำหนดเวลา',
    'news.item2.author': 'ฝ่ายการผลิต',
    'news.item3.title': 'รับใบรับรองมาตรฐาน ISO',
    'news.item3.description': 'บริษัทได้รับใบรับรองมาตรฐาน ISO 9001:2015 ซึ่งแสดงถึงความมุ่งมั่นในการให้บริการที่มีคุณภาพ',
    'news.item3.fullContent': 'บริษัทได้รับใบรับรองมาตรฐาน ISO 9001:2015 ซึ่งเป็นมาตรฐานสากลสำหรับระบบการจัดการคุณภาพ การได้รับใบรับรองนี้แสดงถึงความมุ่งมั่นของบริษัทในการให้บริการที่มีคุณภาพสูงสุดและพัฒนาระบบการทำงานให้มีประสิทธิภาพมากขึ้น',
    'news.item3.author': 'ฝ่ายคุณภาพ',
    'news.item4.title': 'ร่วมงานแสดงสินค้าอุตสาหกรรม',
    'news.item4.description': 'บริษัทเข้าร่วมงานแสดงสินค้าอุตสาหกรรมเพื่อนำเสนอเทคโนโลยีและบริการใหม่ๆ ให้กับลูกค้า',
    'news.item4.fullContent': 'บริษัทได้เข้าร่วมงานแสดงสินค้าอุตสาหกรรมครั้งสำคัญ เพื่อนำเสนอเทคโนโลยีและบริการใหม่ๆ ให้กับลูกค้าและพันธมิตรทางธุรกิจ งานนี้เป็นโอกาสที่ดีในการสร้างเครือข่ายและแสดงศักยภาพของบริษัทในด้านการอบ ชุบ',
    'news.item4.author': 'ฝ่ายการตลาด',
    'news.item5.title': 'อบรมพนักงานด้านความปลอดภัย',
    'news.item5.description': 'จัดอบรมพนักงานด้านความปลอดภัยในการทำงาน เพื่อให้มั่นใจในความปลอดภัยของทุกคน',
    'news.item5.fullContent': 'บริษัทได้จัดอบรมพนักงานด้านความปลอดภัยในการทำงานเป็นประจำ เพื่อให้มั่นใจในความปลอดภัยของทุกคนและลดความเสี่ยงในการเกิดอุบัติเหตุ การอบรมครอบคลุมทั้งทฤษฎีและการปฏิบัติจริง',
    'news.item5.author': 'ฝ่ายความปลอดภัย',
    'news.item6.title': 'เปิดศูนย์วิจัยและพัฒนาใหม่',
    'news.item6.description': 'บริษัทเปิดศูนย์วิจัยและพัฒนาใหม่เพื่อพัฒนานวัตกรรมในด้านการอบ ชุบ',
    'news.item6.fullContent': 'บริษัทได้เปิดศูนย์วิจัยและพัฒนาใหม่ที่ทันสมัย เพื่อพัฒนานวัตกรรมในด้านการอบ ชุบ และสร้างเทคโนโลยีใหม่ๆ ที่จะช่วยเพิ่มประสิทธิภาพการทำงานและคุณภาพของผลิตภัณฑ์',
    'news.item6.author': 'ฝ่ายวิจัยและพัฒนา',
    'news.item7.title': 'ร่วมมือกับมหาวิทยาลัย',
    'news.item7.description': 'บริษัทได้ร่วมมือกับมหาวิทยาลัยในการวิจัยและพัฒนานวัตกรรมใหม่',
    'news.item7.fullContent': 'บริษัทได้ลงนามความร่วมมือกับมหาวิทยาลัยชั้นนำในการวิจัยและพัฒนานวัตกรรมใหม่ในด้านการอบ ชุบ ความร่วมมือนี้จะช่วยให้บริษัทสามารถเข้าถึงความรู้และเทคโนโลยีใหม่ๆ ได้มากขึ้น',
    'news.item7.author': 'ฝ่ายวิชาการ',
    'news.item8.title': 'รับรางวัลคุณภาพแห่งปี',
    'news.item8.description': 'บริษัทได้รับรางวัลคุณภาพแห่งปีจากสมาคมอุตสาหกรรม',
    'news.item8.fullContent': 'บริษัทได้รับรางวัลคุณภาพแห่งปีจากสมาคมอุตสาหกรรม ซึ่งเป็นรางวัลที่แสดงถึงความมุ่งมั่นในการให้บริการที่มีคุณภาพสูงสุดและความสำเร็จในการพัฒนาธุรกิจอย่างยั่งยืน',
    'news.item8.author': 'ฝ่ายบริหาร',
    
    // About Page
    'about.hero.business.title': 'ธุรกิจของเรา',
    'about.hero.business.carburizing': 'การชุบคาร์บอน (Carburizing Hardening)',
    'about.hero.business.carbonitriding': 'การชุบคาร์บอนไนไตรด์ (Carbonitriding Hardening)',
    'about.hero.business.quenching': 'การชุบแข็ง (Quenching)',
    'about.hero.business.induction': 'การชุบเหนี่ยวนำ (Induction Hardening)',
    'about.hero.business.tempering': 'การอบคืน (Tempering)',
    'about.hero.business.and_more': 'และอื่นๆ อีกมากมาย',
    'about.hero.certificate.title': 'การรับรองมาตรฐาน',
    'about.hero.certificate.acquisition': 'การรับรองมาตรฐานของโรงงานไทย',
    'about.hero.customer.title': 'ลูกค้าของเรา',
    'about.hero.certificate.subtitle': 'ใบรับรองมาตรฐาน',
    'about.hero.certificate.subtitle_en': '(Certificates)',
    'about.mission.title': 'พันธกิจของเรา',
    'about.mission.main.title': 'พันธกิจหลัก',
    'about.mission.main.desc': 'มุ่งมั่นในการให้บริการอบ ชุบ (Heat Treatment) ที่มีคุณภาพสูงสุด พร้อมสร้างความพึงพอใจให้กับลูกค้าทุกท่าน ด้วยการนำเทคโนโลยีที่ทันสมัยมาประยุกต์ใช้ในการพัฒนาคุณภาพวัสดุ',
    'about.mission.vision.title': 'วิสัยทัศน์',
    'about.mission.vision.desc': 'เป็นผู้นำในอุตสาหกรรมการอบ ชุบ ที่ลูกค้าไว้วางใจ ด้วยการพัฒนาอย่างต่อเนื่อง และการสร้างสรรค์นวัตกรรมใหม่ๆ เพื่อตอบสนองความต้องการของอุตสาหกรรมที่เปลี่ยนแปลงไป',
    'about.mission.values.title': 'ค่านิยม',
    'about.mission.values.desc': 'ความแม่นยำ ความรับผิดชอบ และการทำงานเป็นทีม พร้อมทั้งการพัฒนาตนเองอย่างต่อเนื่องเพื่อให้บริการอบ ชุบ ที่ดีที่สุด',
    'about.mission.commitment.title': 'ความมุ่งมั่นของเรา',
    'about.mission.commitment.desc': 'เรามุ่งมั่นที่จะเป็นส่วนหนึ่งในการขับเคลื่อนอุตสาหกรรมของคุณให้เติบโตอย่างยั่งยืน ด้วยการให้บริการอบ ชุบ ที่เหนือความคาดหวังและสร้างความไว้วางใจในระยะยาว',
    'about.values.title': 'ค่านิยมหลักของเรา',
    'about.values.subtitle': 'ค่านิยมที่เรายึดถือและปฏิบัติในทุกการทำงาน เพื่อสร้างความไว้วางใจ และความพึงพอใจให้กับลูกค้าและพนักงานทุกท่าน',
    'about.values.quality.title': 'คุณภาพ',
    'about.values.quality.desc': 'มุ่งมั่นในการให้บริการอบ ชุบ ที่มีคุณภาพสูงสุดในทุกขั้นตอน',
    'about.values.technology.title': 'เทคโนโลยี',
    'about.values.technology.desc': 'ใช้เครื่องจักรและอุปกรณ์ที่ทันสมัย ควบคุมด้วยระบบดิจิทัล',
    'about.values.precision.title': 'ความแม่นยำ',
    'about.values.precision.desc': 'ควบคุมอุณหภูมิและเวลาอย่างแม่นยำ ตามมาตรฐานสากล',
    'about.values.reliability.title': 'ความน่าเชื่อถือ',
    'about.values.reliability.desc': 'รับประกันคุณภาพและความปลอดภัยของชิ้นงานทุกชิ้น',
    'about.values.innovation.title': 'นวัตกรรม',
    'about.values.innovation.desc': 'พัฒนาอย่างต่อเนื่องด้วยเทคโนโลยีและแนวทางที่ทันสมัย',
    'about.values.excellence.title': 'ความเป็นเลิศ',
    'about.values.excellence.desc': 'มุ่งมั่นสู่ความเป็นเลิศในการให้บริการอบ ชุบ ทุกประเภท',
    'about.values.commitment.title': 'พันธสัญญาของเรา',
    'about.values.commitment.desc': 'เรามุ่งมั่นที่จะดำเนินธุรกิจด้วยความแม่นยำ โปร่งใส และรับผิดชอบ พร้อมทั้งพัฒนาตนเองอย่างต่อเนื่องเพื่อให้บริการอบ ชุบ ที่ดีที่สุดแก่ลูกค้าทุกท่าน',
    
    // Service Machinery
    'service.machinery.specifications': 'ข้อมูลจำเพาะ',
    'service.machinery.available': 'จำนวนที่มี',
    'service.machinery.carburizing_furnace.title': 'เตาเผาชุบคาร์บอน',
    'service.machinery.carburizing_furnace.specifications': '760W × 1,200D × 830H (สูงสุด 1 ตัน)',
    'service.machinery.carburizing_furnace.units': '4 เครื่อง',
    'service.machinery.induction_hardening.title': 'เครื่องชุบเหนี่ยวนำ',
    'service.machinery.induction_hardening.specifications': 'แบบเคลื่อนที่แนวตั้ง (สูงสุด L=650 มม.)',
    'service.machinery.induction_hardening.units': '2 เครื่อง',
    'service.machinery.tempering_furnace.title': 'เตาเผาอบคืน',
    'service.machinery.tempering_furnace.specifications': '760W × 1,200D × 830H (สูงสุด 650°C)',
    'service.machinery.tempering_furnace.units': '3 เครื่อง',
    'service.machinery.vacuum_degreasing.title': 'เครื่องล้างและกำจัดไขมันสุญญากาศ',
    'service.machinery.vacuum_degreasing.specifications': '760W × 1,200D × 830H',
    'service.machinery.vacuum_degreasing.units': '1 เครื่อง',
    'service.machinery.automatic_straightening.title': 'เครื่องดัดตรงอัตโนมัติ',
    'service.machinery.automatic_straightening.specifications': '5 ตัน พร้อมเซ็นเซอร์ AE (สูงสุด L=600 มม.)',
    'service.machinery.automatic_straightening.units': '1 เครื่อง',
    'service.machinery.manual_straightening.title': 'เครื่องดัดตรงด้วยมือ',
    'service.machinery.manual_straightening.specifications': '1 ตัน (สูงสุด L=600 มม.)',
    'service.machinery.manual_straightening.units': '2 เครื่อง',

    // Products Page
    'product.hero.title': 'บริการอบ ชุบ (Heat Treatment)',
    'product.hero.description': 'ให้บริการอบ ชุบ ทุกประเภท ด้วยเทคโนโลยีที่ทันสมัยและทีมงานผู้เชี่ยวชาญ เพื่อเพิ่มคุณภาพและความแข็งแกร่งของวัสดุให้ตรงตามมาตรฐานสากล',
    'product.hero.heat.title': 'เทคโนโลยีความร้อน',
    'product.hero.heat.desc': 'ระบบควบคุมอุณหภูมิที่แม่นยำ',
    'product.hero.treatment.title': 'การอบ ชุบ',
    'product.hero.treatment.desc': 'กระบวนการที่ได้มาตรฐานสากล',
    'product.hero.quality.title': 'คุณภาพสูง',
    'product.hero.quality.desc': 'รับประกันคุณภาพทุกชิ้นงาน',

    'product.showcase.title': 'ประเภทการอบ ชุบ',
    'product.showcase.subtitle': 'บริการอบ ชุบ ครบทุกประเภท เพื่อตอบสนองความต้องการของอุตสาหกรรมต่างๆ',
    'product.showcase.annealing.title': 'การอบอ่อน (Annealing)',
    'product.showcase.annealing.desc': 'กระบวนการอบอ่อนเพื่อลดความแข็งและปรับปรุงโครงสร้างผลึกของโลหะ',
    'product.showcase.annealing.feature1': 'ลดความแข็งของโลหะ',
    'product.showcase.annealing.feature2': 'ปรับปรุงโครงสร้างผลึก',
    'product.showcase.annealing.feature3': 'เพิ่มความเหนียว',
    'product.showcase.annealing.feature4': 'ลดความเค้นภายใน',
    'product.showcase.quenching.title': 'การชุบแข็ง (Quenching)',
    'product.showcase.quenching.desc': 'กระบวนการชุบแข็งเพื่อเพิ่มความแข็งและความต้านทานการสึกหรอ',
    'product.showcase.quenching.feature1': 'เพิ่มความแข็งสูงสุด',
    'product.showcase.quenching.feature2': 'ต้านทานการสึกหรอ',
    'product.showcase.quenching.feature3': 'เพิ่มความแข็งแรง',
    'product.showcase.quenching.feature4': 'ปรับปรุงคุณสมบัติเชิงกล',
    'product.showcase.tempering.title': 'การอบคืน (Tempering)',
    'product.showcase.tempering.desc': 'กระบวนการอบคืนเพื่อลดความเปราะและปรับสมดุลความแข็งกับความเหนียว',
    'product.showcase.tempering.feature1': 'ลดความเปราะ',
    'product.showcase.tempering.feature2': 'ปรับสมดุลความแข็ง',
    'product.showcase.tempering.feature3': 'เพิ่มความเหนียว',
    'product.showcase.tempering.feature4': 'ลดความเค้นภายใน',
    'product.showcase.normalizing.title': 'การอบปกติ (Normalizing)',
    'product.showcase.normalizing.desc': 'กระบวนการอบปกติเพื่อปรับปรุงโครงสร้างผลึกและคุณสมบัติเชิงกล',
    'product.showcase.normalizing.feature1': 'ปรับปรุงโครงสร้างผลึก',
    'product.showcase.normalizing.feature2': 'เพิ่มความแข็งแรง',
    'product.showcase.normalizing.feature3': 'ปรับปรุงคุณสมบัติเชิงกล',
    'product.showcase.normalizing.feature4': 'ลดความเค้นภายใน',
    'product.showcase.carburizing.title': 'การชุบคาร์บอน (Carburizing)',
    'product.showcase.carburizing.desc': 'กระบวนการชุบคาร์บอนเพื่อเพิ่มความแข็งที่ผิวและความต้านทานการสึกหรอ',
    'product.showcase.carburizing.feature1': 'เพิ่มความแข็งที่ผิว',
    'product.showcase.carburizing.feature2': 'ต้านทานการสึกหรอสูง',
    'product.showcase.carburizing.feature3': 'เพิ่มความแข็งแรง',
    'product.showcase.carburizing.feature4': 'ปรับปรุงคุณสมบัติผิว',
    'product.showcase.nitriding.title': 'การชุบไนโตรเจน (Nitriding)',
    'product.showcase.nitriding.desc': 'กระบวนการชุบไนโตรเจนเพื่อเพิ่มความแข็งที่ผิวและความต้านทานการกัดกร่อน',
    'product.showcase.nitriding.feature1': 'เพิ่มความแข็งที่ผิวสูง',
    'product.showcase.nitriding.feature2': 'ต้านทานการกัดกร่อน',
    'product.showcase.nitriding.feature3': 'เพิ่มความแข็งแรง',
    'product.showcase.nitriding.feature4': 'ปรับปรุงคุณสมบัติผิว',

    'product.features.title': 'จุดเด่นของเรา',
    'product.features.subtitle': 'เราให้บริการอบ ชุบ ด้วยเทคโนโลยีที่ทันสมัยและทีมงานผู้เชี่ยวชาญ เพื่อให้ได้ผลลัพธ์ที่ดีที่สุด',
    'product.features.quality.title': 'คุณภาพสูง',
    'product.features.quality.desc': 'มาตรฐานคุณภาพระดับสากล พร้อมใบรับรองคุณภาพ',
    'product.features.speed.title': 'รวดเร็ว',
    'product.features.speed.desc': 'ส่งมอบงานตรงเวลา พร้อมคุณภาพที่รับประกัน',
    'product.features.technology.title': 'เทคโนโลยีทันสมัย',
    'product.features.technology.desc': 'เครื่องจักรและอุปกรณ์ที่ทันสมัย ควบคุมด้วยระบบดิจิทัล',
    'product.features.precision.title': 'ความแม่นยำ',
    'product.features.precision.desc': 'ควบคุมอุณหภูมิและเวลาอย่างแม่นยำ ตามมาตรฐานสากล',
    'product.features.support.title': 'บริการหลังการขาย',
    'product.features.support.desc': 'ทีมสนับสนุนที่พร้อมช่วยเหลือตลอด 24 ชั่วโมง',
    'product.features.security.title': 'ความปลอดภัย',
    'product.features.security.desc': 'ระบบความปลอดภัยที่ได้มาตรฐาน รับประกันความปลอดภัยของชิ้นงาน',

    'product.process.title': 'กระบวนการทำงาน',
    'product.process.subtitle': 'ขั้นตอนการทำงานที่ชัดเจน โปร่งใส และมีประสิทธิภาพ เพื่อให้ได้ผลลัพธ์ที่ดีที่สุด',
    'product.process.consultation.title': 'ปรึกษาและวิเคราะห์',
    'product.process.consultation.desc': 'วิเคราะห์ความต้องการและกำหนดขอบเขตการทำงาน',
    'product.process.analysis.title': 'ตรวจสอบและวิเคราะห์',
    'product.process.analysis.desc': 'ตรวจสอบวัสดุและวิเคราะห์คุณสมบัติก่อนการอบ ชุบ',
    'product.process.treatment.title': 'การอบ ชุบ',
    'product.process.treatment.desc': 'ดำเนินการอบ ชุบ ตามมาตรฐานที่กำหนด',
    'product.process.quality.title': 'ตรวจสอบคุณภาพ',
    'product.process.quality.desc': 'ตรวจสอบคุณภาพและทดสอบคุณสมบัติหลังการอบ ชุบ',
    'product.process.delivery.title': 'ส่งมอบงาน',
    'product.process.delivery.desc': 'ส่งมอบงานพร้อมรายงานผลการทดสอบและใบรับรองคุณภาพ',

    'product.parts.title': 'แกลเลอรี่ชิ้นส่วนของเรา',
    'product.parts.subtitle': 'ชมชิ้นส่วนและส่วนประกอบที่ผลิตด้วยคุณภาพสูงของเรา',
    'product.parts.overview.title': 'ภาพรวมชิ้นส่วน',
    'product.parts.overview.desc': 'ชิ้นส่วนที่ผลิตด้วยคุณภาพสูง',
    'product.parts.part2.title': 'ชิ้นส่วนความแม่นยำ 2',
    'product.parts.part2.desc': 'ผลิตด้วยความแม่นยำสูง',
    'product.parts.part3.title': 'ชิ้นส่วนขั้นสูง 3',
    'product.parts.part3.desc': 'เทคโนโลยีการผลิตขั้นสูง',

    // Contact Page
    'contact.hero.title': 'ติดต่อเรา',
    'contact.hero.description': 'เราพร้อมให้บริการและตอบคำถามทุกข้อสงสัย ติดต่อเราวันนี้เพื่อรับคำปรึกษาฟรี',
    'contact.form.title': 'ส่งข้อความถึงเรา',
    'contact.form.description': 'กรอกข้อมูลด้านล่าง เราจะติดต่อกลับภายใน 24 ชั่วโมง',
    'contact.form.name': 'ชื่อ-นามสกุล',
    'contact.form.name_placeholder': 'กรอกชื่อ-นามสกุลของคุณ',
    'contact.form.email': 'อีเมล',
    'contact.form.email_placeholder': 'กรอกอีเมลของคุณ',
    'contact.form.phone': 'เบอร์โทรศัพท์',
    'contact.form.phone_placeholder': 'กรอกเบอร์โทรศัพท์ของคุณ',
    'contact.form.company': 'บริษัท',
    'contact.form.company_placeholder': 'กรอกชื่อบริษัทของคุณ',
    'contact.form.position': 'ตำแหน่งงาน',
    'contact.form.position_placeholder': 'กรอกตำแหน่งงานของคุณ',
    'contact.form.subject': 'หัวข้อ',
    'contact.form.subject_placeholder': 'เลือกหัวข้อที่ต้องการติดต่อ',
    'contact.form.subject_general': 'คำถามทั่วไป',
    'contact.form.subject_support': 'ขอความช่วยเหลือ',
    'contact.form.subject_sales': 'สอบถามราคา',
    'contact.form.subject_partnership': 'ความร่วมมือ',
    'contact.form.subject_other': 'อื่นๆ',
    'contact.form.message': 'ข้อความ',
    'contact.form.message_placeholder': 'กรอกรายละเอียดที่ต้องการติดต่อ',
    'contact.form.submit': 'ส่งข้อความ',
    'contact.form.submitting': 'กำลังส่ง...',
    'contact.form.success': 'ส่งข้อความสำเร็จ! เราจะติดต่อกลับโดยเร็วที่สุด',
    'contact.form.error': 'เกิดข้อผิดพลาด กรุณาลองใหม่อีกครั้ง',
    'contact.form.error.company': 'กรุณากรอกชื่อบริษัท',
    'contact.form.error.name': 'กรุณากรอกชื่อ-นามสกุล',
    'contact.form.error.email': 'กรุณากรอกอีเมล',
    'contact.form.error.email_invalid': 'รูปแบบอีเมลไม่ถูกต้อง',
    'contact.form.error.phone': 'กรุณากรอกเบอร์โทรศัพท์',
    'contact.form.error.position': 'กรุณากรอกตำแหน่งงาน',
    'contact.form.error.message': 'กรุณากรอกข้อความ',
    'contact.info.title': 'ข้อมูลติดต่อ',
    'contact.info.description': 'ติดต่อเราได้หลายช่องทาง เราพร้อมให้บริการและตอบคำถามทุกข้อสงสัย',
    'contact.info.email.title': 'อีเมล',
    'contact.info.email.description': 'ส่งอีเมลถึงเราได้ตลอด 24 ชั่วโมง',
    'contact.info.phone.title': 'โทรศัพท์',
    'contact.info.phone.description': 'โทรหาเราในเวลาทำการ',
    'contact.info.address.title': 'ที่อยู่',
    'contact.info.address.description': 'เยี่ยมชมสำนักงานของเรา',
    'contact.info.hours.title': 'เวลาทำการ',
    'contact.info.hours.description': 'เวลาที่เราพร้อมให้บริการ',
    'contact.info.social.title': 'ติดตามเรา',
    'contact.map.title': 'แผนที่และเส้นทาง',
    'contact.map.description': 'ค้นหาเส้นทางมาสำนักงานของเราได้ง่ายๆ',
    'contact.map.placeholder.title': 'แผนที่',
    'contact.map.placeholder.description': 'แผนที่จะแสดงที่นี่',
    'contact.map.placeholder.button': 'เปิดแผนที่',
    'contact.map.directions.title': 'เส้นทางมา',
    'contact.map.directions.bts': 'BTS อโศก - ทางออก 6',
    'contact.map.directions.mrt': 'MRT สุขุมวิท - ทางออก 3',
    'contact.map.directions.parking': 'ที่จอดรถในอาคาร',
    'contact.map.nearby.title': 'สถานที่ใกล้เคียง',
    'contact.map.nearby.terminal21': 'เทอร์มินอล 21',
    'contact.map.nearby.emquartier': 'เอ็มควอเทียร์',
    'contact.map.nearby.benjasiri': 'สวนเบญจกิติ',
    'contact.map.nearby.lumpini': 'สวนลุมพินี',
    'contact.company.name': 'NAGATO HEAT TREATMENT (THAILAND) CO.,LTD.',
    'contact.company.address.title': 'ที่ตั้ง',
    'contact.company.phone.title': 'โทรศัพท์',
    'contact.company.hours.title': 'เวลาทำการ',
    'contact.company.address.detail': '7/379 หมู่ที่ 6 นิคมอุตสาหกรรมอมตะซิตี้<br />ตำบลมาบยางพร อำเภอปลวกแดง<br />จังหวัดระยอง 21140',
    'contact.company.phone.detail': '038-027-473-4<br /><span class="text-sky-600 font-medium">038-027-475 (แฟกซ์)</span>',
    'contact.company.hours.detail': 'จันทร์ - ศุกร์: 07:30 - 16:30<br />เสาร์: 8:00 - 12:00<br />อาทิตย์: ปิดบริการ',
    
    // Company Info Section
    'company.title': 'บริษัท นากาโตะ ฮีท ทรีทเม้นท์',
    'company.subtitle': '(ประเทศไทย) จำกัด',
    'company.info.title': 'ข้อมูลบริษัท',
    'company.info.address': 'ที่อยู่',
    'company.info.phone': 'โทรศัพท์',
    'company.info.established': 'ก่อตั้งเมื่อ',
    'company.info.address_detail': '7/379 Moo 6, Tambol Mabyangporn, Amphur Pluakdaeng Rayong, 21140 Thailand',
    'company.info.phone_detail': '038-027-473-4',
    'company.info.established_detail': 'มกราคม 2556',
    'company.quality.title': 'นโยบายคุณภาพ',
    'company.quality.point1': 'มุ่งมั่นผลิตสินค้าด้วยความจริงใจ เพื่อสร้างความพึงพอใจให้กับลูกค้า',
    'company.quality.point2': 'ปรับปรุงอย่างต่อเนื่อง เพื่อส่งมอบคุณภาพและการบริการที่ดีให้กับลูกค้า',
    'company.slogan.title': 'สโลแกน',
    'company.slogan.text': 'การผลิตที่ยืดหยุ่น',
    
    // 404 Page
    '404.title': '404',
    '404.subtitle': 'ไม่พบหน้าที่คุณกำลังมองหา',
    '404.description': 'ขออภัย หน้าที่คุณกำลังมองหาไม่มีอยู่หรืออาจถูกย้ายไปแล้ว',
    '404.suggestions': 'ข้อเสนอแนะ',
    '404.suggestion1': 'ตรวจสอบ URL ที่คุณป้อน',
    '404.suggestion2': 'กลับไปหน้าแรก',
    '404.suggestion3': 'ใช้เมนูนำทางด้านบน',
    '404.suggestion4': 'ติดต่อเราหากคุณคิดว่านี่เป็นข้อผิดพลาด',
    '404.backHome': 'กลับไปหน้าแรก',
    '404.contactUs': 'ติดต่อเรา',
  },
  en: {
    // NavBar
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.services': 'Services',
    'nav.products': 'Products',
    'nav.inspection': 'Inspection Facility',
    'nav.contact': 'Contact',
    'nav.business_hours': 'Business Hours: Mon-Fri 07:30-16:30',
    'nav.phone': '038-027-473-4',
    'nav.email': 'info@nagato.co.th',
    
    // Inspection Facility
    'inspection.title': 'Workpiece Inspection According to Customer Requirements',
    'inspection.description': 'Workpiece inspection and testing system with modern equipment to ensure quality and standards according to customer requirements',
    'inspection.equipment.magnetic.title': 'Magnetic Particle Testing Machine',
    'inspection.equipment.magnetic.spec': 'Workpiece inspection according to customer requirements',
    'inspection.equipment.rockwell.title': 'ROCKWELL TYPE HARDNESS TESTER',
    'inspection.equipment.rockwell.spec': 'FUTURE-TECH FR-1AN',
    'inspection.equipment.vickers.title': 'VICKERS HARDNESS TESTER',
    'inspection.equipment.vickers.spec': 'FUTURE-TECH FM-300e',
    'inspection.equipment.micro.title': 'MICRO-VICKERS HARDNESS TESTER',
    'inspection.equipment.micro.spec': 'FUTURE-TECH FM-300',
    'inspection.equipment.microscope.title': 'INVERTED METALLURGICAL MICROSCOPES',
    'inspection.equipment.microscope.spec': 'OLYMPUS GX51 Expand X 1000',
    'inspection.equipment.units': '1 unit',
    'inspection.equipment.specifications': 'Specifications',
    'inspection.equipment.available': 'Available',
    
    // Footer
    'footer.company_description': 'NAGATO HEAT TREATMENT (THAILAND) CO., LTD.',
    'footer.quick_links': 'Quick Links',
    'footer.contact_us': 'Contact Us',
    'footer.location': 'Location',
    'footer.address_line1': '7/379 Moo 6 Amata City Industrial Estate',
    'footer.address_line2': 'Tambon Mab Yang Porn, Amphur Pluak Daeng',
    'footer.address_line3': 'Rayong Province 21140',
    'footer.copyright': 'NAGATO HEAT TREATMENT (THAILAND) CO., LTD. All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.phone': '038-027-473-4',
    'footer.fax': '038-027-473-4',
    
    // Meta
    'meta.title': 'Your Company - High Quality Services',
    'meta.description': 'Our company is committed to providing the highest quality services with professional teams and modern technology.',
    
    // Home Page
    'home.hero.title': '',
    'home.hero.subtitle': 'NAGATO HEAT TREATMENT CO.,LTD.',
    'home.hero.description': 'Committed to producing products with sincerity to create customer satisfaction\nContinuously improving to deliver quality and excellent service to customers',
    'home.hero.cta1': 'Get Started',
    'home.hero.cta2': 'Learn More',
    'home.hero.scroll': 'Scroll',
    'home.features.title': 'Why Choose Us',
    'home.features.subtitle': 'We are committed to providing the best heat treatment service with modern technology and expert teams.',
    'home.features.technology.title': 'Modern Technology',
    'home.features.technology.desc': 'Modern machinery and equipment controlled by digital systems for maximum precision.',
    'home.features.quality.title': 'High Quality',
    'home.features.quality.desc': 'International quality standards with quality certificates, guaranteeing results that exceed expectations.',
    'home.features.precision.title': 'Precision',
    'home.features.precision.desc': 'Precise temperature and time control according to international standards for consistent results.',
    'home.features.reliability.title': 'Reliability',
    'home.features.reliability.desc': 'Guaranteeing quality and safety of every workpiece with strict quality inspection systems.',
    'home.features.innovation.title': 'Innovation',
    'home.features.innovation.desc': 'Continuous development with modern technology and approaches to meet changing needs.',
    'home.features.support.title': 'After-Sales Service',
    'home.features.support.desc': 'Support team ready to help you 24/7 with consultation and problem-solving.',
    'home.about.title': 'About Us',
    'home.about.desc1': 'Nagato is a company engaged in development, design, and providing all types of heat treatment services with modern technology and expert teams to enhance material quality and strength according to international standards.',
    'home.about.desc2': 'With our commitment to providing the best heat treatment service, we have gained trust from customers nationwide and are ready to be part of driving your industry to success.',
    'home.about.cta': 'Learn More',
    'home.about.stats.customers': 'Trusted Customers',
    'home.about.stats.quality': 'Quality Guaranteed',
    'home.about.stats.support': 'Support Service',
    'home.about.stats.experience': 'Years Experience',
    'home.cta.title': 'Ready to Get Started?',
    'home.cta.description': 'Join us and experience the best heat treatment service with support from our professional team.',
    'home.cta.button1': 'Start Free',
    'home.cta.button2': 'Contact Us',
    'home.cta.trust': 'Trusted by Leading Companies',
    'home.cta.trust1': 'Automotive Industry',
    'home.cta.trust2': 'Machinery Industry',
    'home.cta.trust3': 'Aerospace Industry',
    'home.cta.trust4': 'Energy Industry',
    
    // News Section
    'home.news.title': 'News & Updates',
    'home.news.subtitle': 'Stay updated with the latest news about heat treatment technology and company developments',
    'home.news.readMore': 'Read More',
    'home.news.viewAll': 'View All News',
    'home.news.item1.title': 'Latest Heat Treatment Technology',
    'home.news.item1.description': 'The company has implemented the most advanced heat treatment technology to enhance work efficiency and quality',
    'home.news.item1.category': 'Technology',
    'home.news.item2.title': 'Production Capacity Expansion',
    'home.news.item2.description': 'To meet increasing demand, the company has expanded production capacity and added new machinery',
    'home.news.item2.category': 'News',
    'home.news.item3.title': 'ISO Standard Certification',
    'home.news.item3.description': 'The company received ISO 9001:2015 certification, demonstrating commitment to quality service',
    'home.news.item3.category': 'Achievement',
    'home.news.item4.title': 'Industrial Exhibition Participation',
    'home.news.item4.description': 'The company participated in industrial exhibitions to showcase new technologies and services to customers',
    'home.news.item4.category': 'Events',
    'home.news.item5.title': 'Employee Safety Training',
    'home.news.item5.description': 'Conducted safety training for employees to ensure workplace safety for everyone',
    'home.news.item5.category': 'Staff Development',
    
    // News Page
    'news.pageTitle': 'All News',
    'news.pageSubtitle': 'Stay updated with the latest news and updates from the company',
    'news.backToHome': 'Back to Home',
    'news.readMore': 'Read More',
    'news.close': 'Close',
    'news.item1.title': 'Latest Heat Treatment Technology',
    'news.item1.description': 'The company has implemented the most advanced heat treatment technology to enhance work efficiency and quality',
    'news.item1.fullContent': 'NAGATO HEAT TREATMENT (THAILAND) CO.,LTD. has implemented the most advanced heat treatment technology in the production process to enhance work efficiency and quality. This new technology will help improve temperature and time control accuracy while reducing energy consumption and increasing workplace safety.',
    'news.item1.author': 'News Team',
    'news.item2.title': 'Production Capacity Expansion',
    'news.item2.description': 'To meet increasing demand, the company has expanded production capacity and added new machinery',
    'news.item2.fullContent': 'Due to business growth and increasing demand, the company has decided to expand production capacity by adding new modern machinery and equipment, as well as expanding production areas to accommodate more customers and deliver work on time.',
    'news.item2.author': 'Production Department',
    'news.item3.title': 'ISO Standard Certification',
    'news.item3.description': 'The company received ISO 9001:2015 certification, demonstrating commitment to quality service',
    'news.item3.fullContent': 'The company received ISO 9001:2015 certification, which is an international standard for quality management systems. This certification demonstrates the company\'s commitment to providing the highest quality service and improving work system efficiency.',
    'news.item3.author': 'Quality Department',
    'news.item4.title': 'Industrial Exhibition Participation',
    'news.item4.description': 'The company participated in industrial exhibitions to showcase new technologies and services to customers',
    'news.item4.fullContent': 'The company participated in an important industrial exhibition to showcase new technologies and services to customers and business partners. This event was a great opportunity to build networks and demonstrate the company\'s capabilities in heat treatment.',
    'news.item4.author': 'Marketing Department',
    'news.item5.title': 'Employee Safety Training',
    'news.item5.description': 'Conducted safety training for employees to ensure workplace safety for everyone',
    'news.item5.fullContent': 'The company regularly conducts workplace safety training for employees to ensure everyone\'s safety and reduce the risk of accidents. The training covers both theory and practical application.',
    'news.item5.author': 'Safety Department',
    'news.item6.title': 'New R&D Center Opening',
    'news.item6.description': 'The company opened a new research and development center to develop innovations in heat treatment',
    'news.item6.fullContent': 'The company has opened a new modern research and development center to develop innovations in heat treatment and create new technologies that will help improve work efficiency and product quality.',
    'news.item6.author': 'R&D Department',
    'news.item7.title': 'University Partnership',
    'news.item7.description': 'The company partnered with universities in research and development of new innovations',
    'news.item7.fullContent': 'The company signed a cooperation agreement with leading universities in research and development of new innovations in heat treatment. This partnership will help the company access new knowledge and technologies.',
    'news.item7.author': 'Academic Department',
    'news.item8.title': 'Quality Award of the Year',
    'news.item8.description': 'The company received the Quality Award of the Year from the Industrial Association',
    'news.item8.fullContent': 'The company received the Quality Award of the Year from the Industrial Association, which is an award that demonstrates commitment to providing the highest quality service and success in sustainable business development.',
    'news.item8.author': 'Management Department',
    
    // About Page
    'about.hero.business.title': 'Business Content',
    'about.hero.business.carburizing': 'Carburizing Hardening',
    'about.hero.business.carbonitriding': 'Carbonitriding Hardening',
    'about.hero.business.quenching': 'Quenching',
    'about.hero.business.induction': 'Induction Hardening',
    'about.hero.business.tempering': 'Tempering',
    'about.hero.business.and_more': 'And Many More',
    'about.hero.certificate.title': 'Certifications',
    'about.hero.certificate.acquisition': 'Certificate acquisition of Thai plant',
    'about.hero.customer.title': 'Our Customers',
    'about.hero.certificate.subtitle': 'Standard Certificates',
    'about.hero.certificate.subtitle_en': '(Certificates)',
    'about.mission.title': 'Our Mission',
    'about.mission.main.title': 'Main Mission',
    'about.mission.main.desc': 'Committed to providing the highest quality heat treatment services while creating satisfaction for all customers by applying modern technology to enhance material quality.',
    'about.mission.vision.title': 'Vision',
    'about.mission.vision.desc': 'To be a leader in the heat treatment industry that customers trust through continuous development and creating new innovations to meet changing industrial needs.',
    'about.mission.values.title': 'Values',
    'about.mission.values.desc': 'Precision, responsibility, and teamwork, along with continuous self-development to provide the best heat treatment service.',
    'about.mission.commitment.title': 'Our Commitment',
    'about.mission.commitment.desc': 'We are committed to being part of driving your industry to grow sustainably by providing heat treatment services that exceed expectations and build long-term trust.',
    'about.values.title': 'Our Core Values',
    'about.values.subtitle': 'Values that we uphold and practice in all our work to build trust and satisfaction for all customers and employees.',
    'about.values.quality.title': 'Quality',
    'about.values.quality.desc': 'Committed to providing the highest quality heat treatment services in every step',
    'about.values.technology.title': 'Technology',
    'about.values.technology.desc': 'Using modern machinery and equipment controlled by digital systems',
    'about.values.precision.title': 'Precision',
    'about.values.precision.desc': 'Precise temperature and time control according to international standards',
    'about.values.reliability.title': 'Reliability',
    'about.values.reliability.desc': 'Guaranteeing quality and safety of every workpiece',
    'about.values.innovation.title': 'Innovation',
    'about.values.innovation.desc': 'Continuous development with modern technology and approaches',
    'about.values.excellence.title': 'Excellence',
    'about.values.excellence.desc': 'Striving for excellence in providing all types of heat treatment services',
    'about.values.commitment.title': 'Our Commitment',
    'about.values.commitment.desc': 'We are committed to conducting business with precision, transparency, and responsibility while continuously developing ourselves to provide the best heat treatment service to all our customers.',
    
    // Service Machinery
    'service.machinery.specifications': 'Specifications',
    'service.machinery.available': 'Available',
    'service.machinery.carburizing_furnace.title': 'Carburizing Hardening Furnace',
    'service.machinery.carburizing_furnace.specifications': '760W × 1,200D × 830H (Max 1 Ton)',
    'service.machinery.carburizing_furnace.units': '4 units',
    'service.machinery.induction_hardening.title': 'Induction Hardening Machine',
    'service.machinery.induction_hardening.specifications': 'Vertical movement type (Max L=650 mm)',
    'service.machinery.induction_hardening.units': '2 units',
    'service.machinery.tempering_furnace.title': 'Tempering Furnace',
    'service.machinery.tempering_furnace.specifications': '760W × 1,200D × 830H (Max 650°C)',
    'service.machinery.tempering_furnace.units': '3 units',
    'service.machinery.vacuum_degreasing.title': 'Vacuum Degreasing and Washing Machine',
    'service.machinery.vacuum_degreasing.specifications': '760W × 1,200D × 830H',
    'service.machinery.vacuum_degreasing.units': '1 unit',
    'service.machinery.automatic_straightening.title': 'Automatic Straightening Machine',
    'service.machinery.automatic_straightening.specifications': '5 Ton with AE sensor (Max L=600 mm)',
    'service.machinery.automatic_straightening.units': '1 unit',
    'service.machinery.manual_straightening.title': 'Manual Straightening Machine',
    'service.machinery.manual_straightening.specifications': '1 Ton (Max L=600 mm)',
    'service.machinery.manual_straightening.units': '2 units',

    // Products Page
    'product.hero.title': 'Heat Treatment Services',
    'product.hero.description': 'We provide all types of heat treatment services with modern technology and expert teams to enhance material quality and strength according to international standards.',
    'product.hero.heat.title': 'Heat Technology',
    'product.hero.heat.desc': 'Precise temperature control systems',
    'product.hero.treatment.title': 'Heat Treatment',
    'product.hero.treatment.desc': 'Processes that meet international standards',
    'product.hero.quality.title': 'High Quality',
    'product.hero.quality.desc': 'Quality guaranteed for every piece',

    'product.showcase.title': 'Heat Treatment Types',
    'product.showcase.subtitle': 'Complete heat treatment services to meet the needs of various industries',
    'product.showcase.annealing.title': 'Annealing',
    'product.showcase.annealing.desc': 'Annealing process to reduce hardness and improve metal crystal structure',
    'product.showcase.annealing.feature1': 'Reduce metal hardness',
    'product.showcase.annealing.feature2': 'Improve crystal structure',
    'product.showcase.annealing.feature3': 'Increase toughness',
    'product.showcase.annealing.feature4': 'Reduce internal stress',
    'product.showcase.quenching.title': 'Quenching',
    'product.showcase.quenching.desc': 'Quenching process to increase hardness and wear resistance',
    'product.showcase.quenching.feature1': 'Maximum hardness increase',
    'product.showcase.quenching.feature2': 'Wear resistance',
    'product.showcase.quenching.feature3': 'Increase strength',
    'product.showcase.quenching.feature4': 'Improve mechanical properties',
    'product.showcase.tempering.title': 'Tempering',
    'product.showcase.tempering.desc': 'Tempering process to reduce brittleness and balance hardness with toughness',
    'product.showcase.tempering.feature1': 'Reduce brittleness',
    'product.showcase.tempering.feature2': 'Balance hardness',
    'product.showcase.tempering.feature3': 'Increase toughness',
    'product.showcase.tempering.feature4': 'Reduce internal stress',
    'product.showcase.normalizing.title': 'Normalizing',
    'product.showcase.normalizing.desc': 'Normalizing process to improve crystal structure and mechanical properties',
    'product.showcase.normalizing.feature1': 'Improve crystal structure',
    'product.showcase.normalizing.feature2': 'Increase strength',
    'product.showcase.normalizing.feature3': 'Improve mechanical properties',
    'product.showcase.normalizing.feature4': 'Reduce internal stress',
    'product.showcase.carburizing.title': 'Carburizing',
    'product.showcase.carburizing.desc': 'Carburizing process to increase surface hardness and wear resistance',
    'product.showcase.carburizing.feature1': 'Increase surface hardness',
    'product.showcase.carburizing.feature2': 'High wear resistance',
    'product.showcase.carburizing.feature3': 'Increase strength',
    'product.showcase.carburizing.feature4': 'Improve surface properties',
    'product.showcase.nitriding.title': 'Nitriding',
    'product.showcase.nitriding.desc': 'Nitriding process to increase surface hardness and corrosion resistance',
    'product.showcase.nitriding.feature1': 'High surface hardness',
    'product.showcase.nitriding.feature2': 'Corrosion resistance',
    'product.showcase.nitriding.feature3': 'Increase strength',
    'product.showcase.nitriding.feature4': 'Improve surface properties',

    'product.features.title': 'Our Highlights',
    'product.features.subtitle': 'We provide heat treatment services with modern technology and expert teams for the best results',
    'product.features.quality.title': 'High Quality',
    'product.features.quality.desc': 'International quality standards with quality certificates',
    'product.features.speed.title': 'Fast',
    'product.features.speed.desc': 'On-time delivery with guaranteed quality',
    'product.features.technology.title': 'Modern Technology',
    'product.features.technology.desc': 'Modern machinery and equipment controlled by digital systems',
    'product.features.precision.title': 'Precision',
    'product.features.precision.desc': 'Precise temperature and time control according to international standards',
    'product.features.support.title': 'After-Sales Service',
    'product.features.support.desc': 'Support team ready to help 24/7',
    'product.features.security.title': 'Security',
    'product.features.security.desc': 'Standard security system guaranteeing workpiece safety',

    'product.process.title': 'Our Process',
    'product.process.subtitle': 'Clear, transparent, and efficient steps for the best results',
    'product.process.consultation.title': 'Consultation & Analysis',
    'product.process.consultation.desc': 'Analyze requirements and define scope of work',
    'product.process.analysis.title': 'Inspection & Analysis',
    'product.process.analysis.desc': 'Inspect materials and analyze properties before heat treatment',
    'product.process.treatment.title': 'Heat Treatment',
    'product.process.treatment.desc': 'Perform heat treatment according to specified standards',
    'product.process.quality.title': 'Quality Inspection',
    'product.process.quality.desc': 'Inspect quality and test properties after heat treatment',
    'product.process.delivery.title': 'Delivery',
    'product.process.delivery.desc': 'Deliver work with test reports and quality certificates',

    'product.parts.title': 'Our Parts Gallery',
    'product.parts.subtitle': 'Explore our high-quality manufactured parts and components',
    'product.parts.overview.title': 'Parts Overview',
    'product.parts.overview.desc': 'High-quality manufactured parts',
    'product.parts.part2.title': 'Precision Part 2',
    'product.parts.part2.desc': 'Engineered with precision',
    'product.parts.part3.title': 'Advanced Part 3',
    'product.parts.part3.desc': 'Advanced manufacturing technology',

    // Contact Page
    'contact.hero.title': 'Contact Us',
    'contact.hero.description': 'We are ready to serve and answer all your questions. Contact us today for a free consultation.',
    'contact.form.title': 'Send us a Message',
    'contact.form.description': 'Fill in the information below. We will get back to you within 24 hours.',
    'contact.form.name': 'Full Name',
    'contact.form.name_placeholder': 'Enter your full name',
    'contact.form.email': 'Email',
    'contact.form.email_placeholder': 'Enter your email',
    'contact.form.phone': 'Phone Number',
    'contact.form.phone_placeholder': 'Enter your phone number',
    'contact.form.company': 'Company',
    'contact.form.company_placeholder': 'Enter your company name',
    'contact.form.position': 'Position',
    'contact.form.position_placeholder': 'Enter your position',
    'contact.form.subject': 'Subject',
    'contact.form.subject_placeholder': 'Select the subject you want to contact about',
    'contact.form.subject_general': 'General Inquiry',
    'contact.form.subject_support': 'Support Request',
    'contact.form.subject_sales': 'Sales Inquiry',
    'contact.form.subject_partnership': 'Partnership',
    'contact.form.subject_other': 'Other',
    'contact.form.message': 'Message',
    'contact.form.message_placeholder': 'Enter the details you want to contact about',
    'contact.form.submit': 'Send Message',
    'contact.form.submitting': 'Sending...',
    'contact.form.success': 'Message sent successfully! We will get back to you as soon as possible.',
    'contact.form.error': 'An error occurred. Please try again.',
    'contact.form.error.company': 'Please enter company name',
    'contact.form.error.name': 'Please enter your name',
    'contact.form.error.email': 'Please enter email',
    'contact.form.error.email_invalid': 'Invalid email format',
    'contact.form.error.phone': 'Please enter phone number',
    'contact.form.error.position': 'Please enter your position',
    'contact.form.error.message': 'Please enter message',
    'contact.info.title': 'Contact Information',
    'contact.info.description': 'You can contact us through various channels. We are ready to serve and answer all your questions.',
    'contact.info.email.title': 'Email',
    'contact.info.email.description': 'Send us an email anytime, 24/7',
    'contact.info.phone.title': 'Phone',
    'contact.info.phone.description': 'Call us during business hours',
    'contact.info.address.title': 'Address',
    'contact.info.address.description': 'Visit our office',
    'contact.info.hours.title': 'Business Hours',
    'contact.info.hours.description': 'Hours when we are ready to serve',
    'contact.info.social.title': 'Follow Us',
    'contact.map.title': 'Map & Directions',
    'contact.map.description': 'Find your way to our office easily',
    'contact.map.placeholder.title': 'Map',
    'contact.map.placeholder.description': 'Map will be displayed here',
    'contact.map.placeholder.button': 'Open Map',
    'contact.map.directions.title': 'How to Get Here',
    'contact.map.directions.bts': 'BTS Asok - Exit 6',
    'contact.map.directions.mrt': 'MRT Sukhumvit - Exit 3',
    'contact.map.directions.parking': 'Building parking available',
    'contact.map.nearby.title': 'Nearby Places',
    'contact.map.nearby.terminal21': 'Terminal 21',
    'contact.map.nearby.emquartier': 'EmQuartier',
    'contact.map.nearby.benjasiri': 'Benjasiri Park',
    'contact.map.nearby.lumpini': 'Lumpini Park',
    'contact.company.name': 'NAGATO HEAT TREATMENT (THAILAND) CO.,LTD.',
    'contact.company.address.title': 'Address',
    'contact.company.phone.title': 'Phone',
    'contact.company.hours.title': 'Business Hours',
    'contact.company.address.detail': '7/379 Moo 6 Amata City Industrial Estate<br />Tambon Mab Yang Porn, Amphur Pluak Daeng<br />Rayong Province 21140',
    'contact.company.phone.detail': '038-027-473-4<br /><span class="text-sky-600 font-medium">038-027-475 (Fax)</span>',
    'contact.company.hours.detail': 'Monday - Friday: 07:30 - 16:30<br />Saturday: 8:00 - 12:00<br />Sunday: Closed',
    
    // Company Info Section
    'company.title': 'NAGATO HEAT TREATMENT',
    'company.subtitle': '(THAILAND) CO., LTD.',
    'company.info.title': 'Company Information',
    'company.info.address': 'Address',
    'company.info.phone': 'Phone',
    'company.info.established': 'Established',
    'company.info.address_detail': '7/379 Moo 6, Tambol Mabyangporn, Amphur Pluakdaeng Rayong, 21140 Thailand',
    'company.info.phone_detail': '038-027-473-4',
    'company.info.established_detail': 'January 2013',
    'company.quality.title': 'Quality Policy',
    'company.quality.point1': 'Committed to producing products with sincerity to create customer satisfaction',
    'company.quality.point2': 'Continuously improving to deliver quality and excellent service to customers',
    'company.slogan.title': 'Slogan',
    'company.slogan.text': 'Flexible Production',
    
    // 404 Page
    '404.title': '404',
    '404.subtitle': 'Page Not Found',
    '404.description': 'Sorry, the page you are looking for does not exist or may have been moved.',
    '404.suggestions': 'Suggestions',
    '404.suggestion1': 'Check the URL you entered',
    '404.suggestion2': 'Go back to the home page',
    '404.suggestion3': 'Use the navigation menu above',
    '404.suggestion4': 'Contact us if you think this is an error',
    '404.backHome': 'Back to Home',
    '404.contactUs': 'Contact Us',
  },
  jp: {
    // NavBar
    'nav.home': 'ホーム',
    'nav.about': '会社概要',
    'nav.services': 'サービス',
    'nav.products': '製品',
    'nav.inspection': '検査施設',
    'nav.contact': 'お問い合わせ',
    'nav.business_hours': '営業時間: 月-金 07:30-16:30',
    'nav.phone': '038-027-473-4',
    'nav.email': 'info@nagato.co.th',
    
    // Inspection Facility
    'inspection.title': 'お客様の要件に応じた部品検査',
    'inspection.description': '最新の機器を使用した部品検査・テストシステムにより、お客様の要件に応じた品質と標準を確保します',
    'inspection.equipment.magnetic.title': 'Magnetic Particle Testing Machine',
    'inspection.equipment.magnetic.spec': 'お客様の要件に応じた部品検査',
    'inspection.equipment.rockwell.title': 'ROCKWELL TYPE HARDNESS TESTER',
    'inspection.equipment.rockwell.spec': 'FUTURE-TECH FR-1AN',
    'inspection.equipment.vickers.title': 'VICKERS HARDNESS TESTER',
    'inspection.equipment.vickers.spec': 'FUTURE-TECH FM-300e',
    'inspection.equipment.micro.title': 'MICRO-VICKERS HARDNESS TESTER',
    'inspection.equipment.micro.spec': 'FUTURE-TECH FM-300',
    'inspection.equipment.microscope.title': 'INVERTED METALLURGICAL MICROSCOPES',
    'inspection.equipment.microscope.spec': 'OLYMPUS GX51 Expand X 1000',
    'inspection.equipment.units': '1台',
    'inspection.equipment.specifications': '仕様',
    'inspection.equipment.available': '数量',
    
    // Footer
    'footer.company_description': 'ナガト熱処理（タイランド）株式会社',
    'footer.quick_links': 'クイックリンク',
    'footer.contact_us': 'お問い合わせ',
    'footer.location': '所在地',
    'footer.address_line1': '7/379 ムー6 アマタシティ工業団地',
    'footer.address_line2': 'タンボン・マブヤンプーン、アムプル・プルアクダエン',
    'footer.address_line3': 'ラヨーン県 21140',
    'footer.copyright': 'ナガト熱処理（タイランド）株式会社。全著作権所有。',
    'footer.privacy': 'プライバシーポリシー',
    'footer.terms': '利用規約',
    'footer.phone': '038-027-473-4',
    'footer.fax': '038-027-473-4',
    
    // Meta
    'meta.title': 'あなたの会社 - 高品質サービス',
    'meta.description': '当社は、プロフェッショナルなチームと最新技術で最高品質のサービスを提供することにコミットしています。',
    
    // Home Page
    'home.hero.title': '',
    'home.hero.subtitle': 'ナガト熱処理（タイランド）株式会社',
    'home.hero.description': '誠実さを持って製品を生産し、お客様の満足を創造することに努めます\n継続的に改善し、お客様に品質と優れたサービスを提供します',
    'home.hero.cta1': '始める',
    'home.hero.cta2': '詳細を見る',
    'home.hero.scroll': 'スクロール',
    'home.features.title': 'なぜ私たちを選ぶのか',
    'home.features.subtitle': '最新技術と専門チームで最高の熱処理サービスを提供することにコミットしています。',
    'home.features.technology.title': '最新技術',
    'home.features.technology.desc': '最大の精密性のためにデジタルシステムで制御される最新の機械と設備。',
    'home.features.quality.title': '高品質',
    'home.features.quality.desc': '品質証明書付きの国際品質基準、期待を超える結果を保証。',
    'home.features.precision.title': '精密性',
    'home.features.precision.desc': '国際基準に準拠した精密な温度と時間制御で一貫した結果を実現。',
    'home.features.reliability.title': '信頼性',
    'home.features.reliability.desc': '厳格な品質検査システムで、すべてのワークピースの品質と安全性を保証。',
    'home.features.innovation.title': 'イノベーション',
    'home.features.innovation.desc': '変化するニーズに応えるための最新技術とアプローチによる継続的な開発。',
    'home.features.support.title': 'アフターサービス',
    'home.features.support.desc': 'コンサルティングと問題解決で24時間体制でサポートするサポートチーム。',
    'home.about.title': '会社概要',
    'home.about.desc1': 'Nagatoは、開発、設計、そして最新技術と専門チームで国際基準に準拠した材料の品質と強度を向上させるあらゆるタイプの熱処理サービスを提供する会社です。',
    'home.about.desc2': '最高の熱処理サービスを提供するというコミットメントにより、全国の顧客からの信頼を得ており、お客様の産業を成功に導く一員となる準備ができています。',
    'home.about.cta': '詳細を見る',
    'home.about.stats.customers': '信頼できる顧客',
    'home.about.stats.quality': '品質保証',
    'home.about.stats.support': 'サポートサービス',
    'home.about.stats.experience': '年の経験',
    'home.cta.title': '始める準備はできましたか？',
    'home.cta.description': '私たちに参加して、プロフェッショナルなチームからのサポートで最高の熱処理サービスを体験してください。',
    'home.cta.button1': '無料で始める',
    'home.cta.button2': 'お問い合わせ',
    'home.cta.trust': '主要企業に信頼されています',
    'home.cta.trust1': '自動車産業',
    'home.cta.trust2': '機械産業',
    'home.cta.trust3': '航空宇宙産業',
    'home.cta.trust4': 'エネルギー産業',
    
    // News Section
    'home.news.title': 'ニュース・アップデート',
    'home.news.subtitle': '熱処理技術と会社の発展に関する最新ニュースをお知らせします',
    'home.news.readMore': '続きを読む',
    'home.news.viewAll': 'すべてのニュースを見る',
    'home.news.item1.title': '最新の熱処理技術',
    'home.news.item1.description': '会社は作業効率と品質を向上させるために最も先進的な熱処理技術を導入しました',
    'home.news.item1.category': '技術',
    'home.news.item2.title': '生産能力の拡大',
    'home.news.item2.description': '需要の増加に対応するため、会社は生産能力を拡大し、新しい機械を追加しました',
    'home.news.item2.category': 'ニュース',
    'home.news.item3.title': 'ISO標準認証取得',
    'home.news.item3.description': '会社はISO 9001:2015認証を取得し、品質サービスへの取り組みを示しています',
    'home.news.item3.category': '成果',
    'home.news.item4.title': '産業展示会への参加',
    'home.news.item4.description': '会社は産業展示会に参加し、お客様に新しい技術とサービスを紹介しました',
    'home.news.item4.category': 'イベント',
    'home.news.item5.title': '従業員安全研修',
    'home.news.item5.description': '全員の職場安全を確保するため、従業員向けの安全研修を実施しました',
    'home.news.item5.category': '人材開発',
    
    // News Page
    'news.pageTitle': 'すべてのニュース',
    'news.pageSubtitle': '会社からの最新ニュースとアップデートをお知らせします',
    'news.backToHome': 'ホームに戻る',
    'news.readMore': '続きを読む',
    'news.close': '閉じる',
    'news.item1.title': '最新の熱処理技術',
    'news.item1.description': '会社は作業効率と品質を向上させるために最も先進的な熱処理技術を導入しました',
    'news.item1.fullContent': 'NAGATO HEAT TREATMENT (THAILAND) CO.,LTD.は、作業効率と品質を向上させるために、生産プロセスに最も先進的な熱処理技術を導入しました。この新しい技術により、温度と時間の制御精度が向上し、エネルギー消費を削減し、職場の安全性を高めることができます。',
    'news.item1.author': 'ニュースチーム',
    'news.item2.title': '生産能力の拡大',
    'news.item2.description': '需要の増加に対応するため、会社は生産能力を拡大し、新しい機械を追加しました',
    'news.item2.fullContent': 'ビジネスの成長と需要の増加により、会社は新しい現代的な機械と設備を追加し、生産エリアを拡大することで生産能力を拡大することを決定しました。これにより、より多くの顧客に対応し、時間通りに作業を納品できるようになります。',
    'news.item2.author': '生産部門',
    'news.item3.title': 'ISO標準認証取得',
    'news.item3.description': '会社はISO 9001:2015認証を取得し、品質サービスへの取り組みを示しています',
    'news.item3.fullContent': '会社は品質管理システムの国際標準であるISO 9001:2015認証を取得しました。この認証は、最高品質のサービスを提供し、作業システムの効率を向上させるという会社の取り組みを示しています。',
    'news.item3.author': '品質部門',
    'news.item4.title': '産業展示会への参加',
    'news.item4.description': '会社は産業展示会に参加し、お客様に新しい技術とサービスを紹介しました',
    'news.item4.fullContent': '会社は重要な産業展示会に参加し、お客様やビジネスパートナーに新しい技術とサービスを紹介しました。このイベントは、ネットワークを構築し、熱処理における会社の能力を実証する素晴らしい機会でした。',
    'news.item4.author': 'マーケティング部門',
    'news.item5.title': '従業員安全研修',
    'news.item5.description': '全員の職場安全を確保するため、従業員向けの安全研修を実施しました',
    'news.item5.fullContent': '会社は従業員の職場安全研修を定期的に実施し、全員の安全を確保し、事故のリスクを軽減しています。研修は理論と実践の両方をカバーしています。',
    'news.item5.author': '安全部門',
    'news.item6.title': '新R&Dセンター開設',
    'news.item6.description': '会社は熱処理のイノベーション開発のため、新しい研究開発センターを開設しました',
    'news.item6.fullContent': '会社は熱処理のイノベーション開発と、作業効率と製品品質の向上に役立つ新しい技術の創造のため、新しい現代的な研究開発センターを開設しました。',
    'news.item6.author': 'R&D部門',
    'news.item7.title': '大学とのパートナーシップ',
    'news.item7.description': '会社は大学と新しいイノベーションの研究開発で協力しました',
    'news.item7.fullContent': '会社は熱処理における新しいイノベーションの研究開発で主要大学と協力協定を締結しました。このパートナーシップにより、会社は新しい知識と技術にアクセスできるようになります。',
    'news.item7.author': '学術部門',
    'news.item8.title': '年間品質賞受賞',
    'news.item8.description': '会社は産業協会から年間品質賞を受賞しました',
    'news.item8.fullContent': '会社は産業協会から年間品質賞を受賞しました。これは、最高品質のサービスを提供するという取り組みと持続可能なビジネス開発の成功を示す賞です。',
    'news.item8.author': '管理部門',
    
    // About Page
    'about.hero.business.title': 'ビジネス内容',
    'about.hero.business.carburizing': '浸炭焼入れ (Carburizing Hardening)',
    'about.hero.business.carbonitriding': '浸炭窒化焼入れ (Carbonitriding Hardening)',
    'about.hero.business.quenching': '焼入れ (Quenching)',
    'about.hero.business.induction': '高周波焼入れ (Induction Hardening)',
    'about.hero.business.tempering': '焼戻し (Tempering)',
    'about.hero.business.and_more': 'その他多数',
    'about.hero.certificate.title': '認証',
    'about.hero.certificate.acquisition': 'タイ工場の認証取得',
    'about.hero.customer.title': 'お客様',
    'about.hero.certificate.subtitle': '標準認証',
    'about.hero.certificate.subtitle_en': '(認証書)',
    'about.mission.title': '私たちのミッション',
    'about.mission.main.title': '主要ミッション',
    'about.mission.main.desc': '最新技術を適用して材料の品質を向上させながら、すべてのお客様に満足を提供する最高品質の熱処理サービスを提供することにコミットしています。',
    'about.mission.vision.title': 'ビジョン',
    'about.mission.vision.desc': '継続的な開発と変化する産業ニーズに応える新しいイノベーションの創造を通じて、お客様に信頼される熱処理業界のリーダーになること。',
    'about.mission.values.title': '価値観',
    'about.mission.values.desc': '精密性、責任感、チームワーク、そして最高の熱処理サービスを提供するための継続的な自己開発。',
    'about.mission.commitment.title': '私たちのコミットメント',
    'about.mission.commitment.desc': '期待を超える熱処理サービスを提供し、長期的な信頼を築くことで、お客様の産業を持続可能に成長させる一員となることにコミットしています。',
    'about.values.title': '私たちのコアバリュー',
    'about.values.subtitle': 'すべてのお客様と従業員の信頼と満足を築くために、すべての仕事で守り実践する価値観。',
    'about.values.quality.title': '品質',
    'about.values.quality.desc': 'すべてのステップで最高品質の熱処理サービスを提供することにコミット',
    'about.values.technology.title': '技術',
    'about.values.technology.desc': 'デジタルシステムで制御される最新の機械と設備の使用',
    'about.values.precision.title': '精密性',
    'about.values.precision.desc': '国際基準に準拠した精密な温度と時間制御',
    'about.values.reliability.title': '信頼性',
    'about.values.reliability.desc': 'すべてのワークピースの品質と安全性を保証',
    'about.values.innovation.title': 'イノベーション',
    'about.values.innovation.desc': '最新技術と現代的なアプローチによる継続的な開発',
    'about.values.excellence.title': '卓越性',
    'about.values.excellence.desc': 'あらゆるタイプの熱処理サービスの提供における卓越性の追求',
    'about.values.commitment.title': '私たちのコミットメント',
    'about.values.commitment.desc': '私たちは、精密性、透明性、責任感を持ってビジネスを運営し、すべてのお客様に最高の熱処理サービスを提供するために継続的に自己開発することにコミットしています。',
    
    // Service Machinery
    'service.machinery.specifications': '仕様',
    'service.machinery.available': '在庫数',
    'service.machinery.carburizing_furnace.title': '浸炭焼入れ炉',
    'service.machinery.carburizing_furnace.specifications': '760W × 1,200D × 830H (最大1トン)',
    'service.machinery.carburizing_furnace.units': '4台',
    'service.machinery.induction_hardening.title': '高周波焼入れ機',
    'service.machinery.induction_hardening.specifications': '垂直移動式 (最大L=650mm)',
    'service.machinery.induction_hardening.units': '2台',
    'service.machinery.tempering_furnace.title': '焼戻し炉',
    'service.machinery.tempering_furnace.specifications': '760W × 1,200D × 830H (最大650°C)',
    'service.machinery.tempering_furnace.units': '3台',
    'service.machinery.vacuum_degreasing.title': '真空脱脂・洗浄機',
    'service.machinery.vacuum_degreasing.specifications': '760W × 1,200D × 830H',
    'service.machinery.vacuum_degreasing.units': '1台',
    'service.machinery.automatic_straightening.title': '自動矯正機',
    'service.machinery.automatic_straightening.specifications': '5トン AEセンサー付き (最大L=600mm)',
    'service.machinery.automatic_straightening.units': '1台',
    'service.machinery.manual_straightening.title': '手動矯正機',
    'service.machinery.manual_straightening.specifications': '1トン (最大L=600mm)',
    'service.machinery.manual_straightening.units': '2台',

    // Products Page
    'product.hero.title': '熱処理サービス',
    'product.hero.description': '最新技術と専門チームで、国際基準に準拠した材料の品質と強度を向上させるあらゆるタイプの熱処理サービスを提供します。',
    'product.hero.heat.title': '熱技術',
    'product.hero.heat.desc': '精密な温度制御システム',
    'product.hero.treatment.title': '熱処理',
    'product.hero.treatment.desc': '国際基準を満たすプロセス',
    'product.hero.quality.title': '高品質',
    'product.hero.quality.desc': 'すべての部品の品質保証',

    'product.showcase.title': '熱処理の種類',
    'product.showcase.subtitle': '様々な産業のニーズに応える完全な熱処理サービス',
    'product.showcase.annealing.title': '焼きなまし',
    'product.showcase.annealing.desc': '硬度を下げ、金属の結晶構造を改善する焼きなましプロセス',
    'product.showcase.annealing.feature1': '金属の硬度を下げる',
    'product.showcase.annealing.feature2': '結晶構造を改善',
    'product.showcase.annealing.feature3': '靭性を向上',
    'product.showcase.annealing.feature4': '内部応力を軽減',
    'product.showcase.quenching.title': '焼入れ',
    'product.showcase.quenching.desc': '硬度と耐摩耗性を向上させる焼入れプロセス',
    'product.showcase.quenching.feature1': '最大硬度向上',
    'product.showcase.quenching.feature2': '耐摩耗性',
    'product.showcase.quenching.feature3': '強度向上',
    'product.showcase.quenching.feature4': '機械的特性改善',
    'product.showcase.tempering.title': '焼戻し',
    'product.showcase.tempering.desc': '脆性を減らし、硬度と靭性のバランスを取る焼戻しプロセス',
    'product.showcase.tempering.feature1': '脆性を減らす',
    'product.showcase.tempering.feature2': '硬度のバランス',
    'product.showcase.tempering.feature3': '靭性向上',
    'product.showcase.tempering.feature4': '内部応力軽減',
    'product.showcase.normalizing.title': '焼ならし',
    'product.showcase.normalizing.desc': '結晶構造と機械的特性を改善する焼ならしプロセス',
    'product.showcase.normalizing.feature1': '結晶構造改善',
    'product.showcase.normalizing.feature2': '強度向上',
    'product.showcase.normalizing.feature3': '機械的特性改善',
    'product.showcase.normalizing.feature4': '内部応力軽減',
    'product.showcase.carburizing.title': '浸炭',
    'product.showcase.carburizing.desc': '表面硬度と耐摩耗性を向上させる浸炭プロセス',
    'product.showcase.carburizing.feature1': '表面硬度向上',
    'product.showcase.carburizing.feature2': '高耐摩耗性',
    'product.showcase.carburizing.feature3': '強度向上',
    'product.showcase.carburizing.feature4': '表面特性改善',
    'product.showcase.nitriding.title': '窒化',
    'product.showcase.nitriding.desc': '表面硬度と耐食性を向上させる窒化プロセス',
    'product.showcase.nitriding.feature1': '高表面硬度',
    'product.showcase.nitriding.feature2': '耐食性',
    'product.showcase.nitriding.feature3': '強度向上',
    'product.showcase.nitriding.feature4': '表面特性改善',

    'product.features.title': '私たちの特徴',
    'product.features.subtitle': '最新技術と専門チームで最高の結果を得るための熱処理サービスを提供',
    'product.features.quality.title': '高品質',
    'product.features.quality.desc': '品質証明書付きの国際品質基準',
    'product.features.speed.title': '高速',
    'product.features.speed.desc': '品質保証付きの時間通りの納品',
    'product.features.technology.title': '最新技術',
    'product.features.technology.desc': 'デジタルシステムで制御される最新の機械と設備',
    'product.features.precision.title': '精密性',
    'product.features.precision.desc': '国際基準に準拠した精密な温度と時間制御',
    'product.features.support.title': 'アフターサービス',
    'product.features.support.desc': '24時間体制でサポートするサポートチーム',
    'product.features.security.title': 'セキュリティ',
    'product.features.security.desc': 'ワークピースの安全性を保証する標準セキュリティシステム',

    'product.process.title': '私たちのプロセス',
    'product.process.subtitle': '最高の結果のための明確で透明性があり効率的なステップ',
    'product.process.consultation.title': '相談・分析',
    'product.process.consultation.desc': '要件を分析し、作業範囲を定義',
    'product.process.analysis.title': '検査・分析',
    'product.process.analysis.desc': '熱処理前に材料を検査し、特性を分析',
    'product.process.treatment.title': '熱処理',
    'product.process.treatment.desc': '指定された基準に従って熱処理を実行',
    'product.process.quality.title': '品質検査',
    'product.process.quality.desc': '熱処理後の品質を検査し、特性をテスト',
    'product.process.delivery.title': '納品',
    'product.process.delivery.desc': 'テストレポートと品質証明書付きで作業を納品',

    'product.parts.title': '私たちの部品ギャラリー',
    'product.parts.subtitle': '高品質で製造された部品とコンポーネントをご覧ください',
    'product.parts.overview.title': '部品概要',
    'product.parts.overview.desc': '高品質で製造された部品',
    'product.parts.part2.title': '精密部品 2',
    'product.parts.part2.desc': '精密に設計・製造',
    'product.parts.part3.title': '高度な部品 3',
    'product.parts.part3.desc': '高度な製造技術',

    // Contact Page
    'contact.hero.title': 'お問い合わせ',
    'contact.hero.description': 'お客様のご質問にお答えし、サービスを提供する準備ができています。無料相談は今すぐお問い合わせください。',
    'contact.form.title': 'メッセージを送信',
    'contact.form.description': '以下の情報を入力してください。24時間以内にご連絡いたします。',
    'contact.form.name': 'お名前',
    'contact.form.name_placeholder': 'お名前を入力してください',
    'contact.form.email': 'メールアドレス',
    'contact.form.email_placeholder': 'メールアドレスを入力してください',
    'contact.form.phone': '電話番号',
    'contact.form.phone_placeholder': '電話番号を入力してください',
    'contact.form.company': '会社名',
    'contact.form.company_placeholder': '会社名を入力してください',
    'contact.form.position': '役職',
    'contact.form.position_placeholder': '役職を入力してください',
    'contact.form.subject': '件名',
    'contact.form.subject_placeholder': 'お問い合わせの件名を選択してください',
    'contact.form.subject_general': '一般的なお問い合わせ',
    'contact.form.subject_support': 'サポート依頼',
    'contact.form.subject_sales': '営業お問い合わせ',
    'contact.form.subject_partnership': 'パートナーシップ',
    'contact.form.subject_other': 'その他',
    'contact.form.message': 'メッセージ',
    'contact.form.message_placeholder': 'お問い合わせの詳細を入力してください',
    'contact.form.submit': 'メッセージを送信',
    'contact.form.submitting': '送信中...',
    'contact.form.success': 'メッセージが正常に送信されました！できるだけ早くご連絡いたします。',
    'contact.form.error': 'エラーが発生しました。もう一度お試しください。',
    'contact.form.error.company': '会社名を入力してください',
    'contact.form.error.name': 'お名前を入力してください',
    'contact.form.error.email': 'メールアドレスを入力してください',
    'contact.form.error.email_invalid': 'メールアドレスの形式が正しくありません',
    'contact.form.error.phone': '電話番号を入力してください',
    'contact.form.error.position': '役職を入力してください',
    'contact.form.error.message': 'メッセージを入力してください',
    'contact.info.title': 'お問い合わせ情報',
    'contact.info.description': '様々なチャネルでお問い合わせいただけます。お客様のご質問にお答えし、サービスを提供する準備ができています。',
    'contact.info.email.title': 'メール',
    'contact.info.email.description': '24時間いつでもメールをお送りください',
    'contact.info.phone.title': '電話',
    'contact.info.phone.description': '営業時間内にお電話ください',
    'contact.info.address.title': '住所',
    'contact.info.address.description': 'オフィスにお越しください',
    'contact.info.hours.title': '営業時間',
    'contact.info.hours.description': 'サービス提供時間',
    'contact.info.social.title': 'フォローする',
    'contact.map.title': '地図とアクセス',
    'contact.map.description': 'オフィスへの道のりを簡単に見つけることができます',
    'contact.map.placeholder.title': '地図',
    'contact.map.placeholder.description': '地図がここに表示されます',
    'contact.map.placeholder.button': '地図を開く',
    'contact.map.directions.title': 'アクセス方法',
    'contact.map.directions.bts': 'BTSアソーク - 6番出口',
    'contact.map.directions.mrt': 'MRTスクンビット - 3番出口',
    'contact.map.directions.parking': '建物内駐車場あり',
    'contact.map.nearby.title': '周辺施設',
    'contact.map.nearby.terminal21': 'ターミナル21',
    'contact.map.nearby.emquartier': 'エムクォーティア',
    'contact.map.nearby.benjasiri': 'ベンチャシリ公園',
    'contact.map.nearby.lumpini': 'ルンピニ公園',
    'contact.company.name': 'NAGATO HEAT TREATMENT (THAILAND) CO.,LTD.',
    'contact.company.address.title': '住所',
    'contact.company.phone.title': '電話',
    'contact.company.hours.title': '営業時間',
    'contact.company.address.detail': '7/379 ムー6 アマタシティ工業団地<br />タンボン・マブヤンプーン、アムプル・プルアクダエン<br />ラヨーン県 21140',
    'contact.company.phone.detail': '038-027-473<br /><span class="text-sky-600 font-medium">038-027-473 (ファックス)</span>',
    'contact.company.hours.detail': '月曜日 - 金曜日: 07:30 - 16:30<br />土曜日: 8:00 - 12:00<br />日曜日: 休業',
    
    // Company Info Section
    'company.title': 'ナガト熱処理株式会社',
    'company.subtitle': '(タイランド) 株式会社',
    'company.info.title': '会社情報',
    'company.info.address': '住所',
    'company.info.phone': '電話',
    'company.info.established': '設立',
    'company.info.address_detail': '7/379 ムー6 タンボン・マブヤンプーン、アムプル・プルアクダエン ラヨーン県 21140 タイ',
    'company.info.phone_detail': '038-027-473-4',
    'company.info.established_detail': '2013年1月',
    'company.quality.title': '品質方針',
    'company.quality.point1': '誠実さを持って製品を生産し、お客様の満足を創造することに努めます',
    'company.quality.point2': '継続的に改善し、お客様に品質と優れたサービスを提供します',
    'company.slogan.title': 'スローガン',
    'company.slogan.text': '柔軟な生産',
    
    // 404 Page
    '404.title': '404',
    '404.subtitle': 'ページが見つかりません',
    '404.description': '申し訳ございません。お探しのページは存在しないか、移動された可能性があります。',
    '404.suggestions': '提案',
    '404.suggestion1': '入力したURLを確認してください',
    '404.suggestion2': 'ホームページに戻る',
    '404.suggestion3': '上記のナビゲーションメニューを使用してください',
    '404.suggestion4': 'これがエラーだと思われる場合はお問い合わせください',
    '404.backHome': 'ホームに戻る',
    '404.contactUs': 'お問い合わせ',
  },
  cn: {
    // NavBar
    'nav.home': '首页',
    'nav.about': '关于我们',
    'nav.services': '服务',
    'nav.products': '产品',
    'nav.inspection': '检测设施',
    'nav.contact': '联系我们',
    'nav.business_hours': '营业时间: 周一-周五 07:30-16:30',
    'nav.phone': '038-027-473-4',
    'nav.email': 'info@nagato.co.th',
    
    // Inspection Facility
    'inspection.title': '根据客户要求进行工件检测',
    'inspection.description': '使用现代设备的工件检测和测试系统，确保根据客户要求的质量和标准',
    'inspection.equipment.magnetic.title': '磁粉检测机',
    'inspection.equipment.magnetic.spec': '根据客户要求进行工件检测',
    'inspection.equipment.rockwell.title': '洛氏硬度测试仪',
    'inspection.equipment.rockwell.spec': 'FUTURE-TECH FR-1AN',
    'inspection.equipment.vickers.title': '维氏硬度测试仪',
    'inspection.equipment.vickers.spec': 'FUTURE-TECH FM-300e',
    'inspection.equipment.micro.title': '显微维氏硬度测试仪',
    'inspection.equipment.micro.spec': 'FUTURE-TECH FM-300',
    'inspection.equipment.microscope.title': '倒置金相显微镜',
    'inspection.equipment.microscope.spec': 'OLYMPUS GX51 Expand X 1000',
    'inspection.equipment.units': '1台',
    'inspection.equipment.specifications': '规格',
    'inspection.equipment.available': '数量',
    
    // Footer
    'footer.company_description': '长门热处理（泰国）有限公司',
    'footer.quick_links': '快速链接',
    'footer.contact_us': '联系我们',
    'footer.location': '位置',
    'footer.address_line1': '7/379 6号村 阿玛塔市工业区',
    'footer.address_line2': '马布扬蓬区 普拉达恩县',
    'footer.address_line3': '罗勇府 21140',
    'footer.copyright': '长门热处理（泰国）有限公司。版权所有。',
    'footer.privacy': '隐私政策',
    'footer.terms': '服务条款',
    'footer.phone': '038-027-473-4',
    'footer.fax': '038-027-473-4',
    
    // Meta
    'meta.title': '您的公司 - 高质量服务',
    'meta.description': '我们公司致力于通过专业团队和现代技术提供最高质量的服务。',
    
    // Home Page
    'home.hero.title': '',
    'home.hero.subtitle': '长门热处理（泰国）有限公司',
    'home.hero.description': '致力于以真诚生产产品，为客户创造满意\n持续改进，为客户提供质量和优质服务',
    'home.hero.cta1': '开始使用',
    'home.hero.cta2': '了解更多',
    'home.hero.scroll': '滚动',
    'home.features.title': '为什么选择我们',
    'home.features.subtitle': '我们致力于通过现代技术和专家团队提供最佳的热处理服务。',
    'home.features.technology.title': '现代技术',
    'home.features.technology.desc': '通过数字系统控制的现代机械和设备，实现最大精度。',
    'home.features.quality.title': '高质量',
    'home.features.quality.desc': '国际质量标准，配备质量证书，保证超出期望的结果。',
    'home.features.precision.title': '精度',
    'home.features.precision.desc': '根据国际标准精确控制温度和时间，确保一致的结果。',
    'home.features.reliability.title': '可靠性',
    'home.features.reliability.desc': '通过严格的质量检查系统保证每个工件的质量和安全。',
    'home.features.innovation.title': '创新',
    'home.features.innovation.desc': '通过现代技术和方法持续发展，满足不断变化的需求。',
    'home.features.support.title': '售后服务',
    'home.features.support.desc': '支持团队24/7为您提供咨询和问题解决服务。',
    'home.about.title': '关于我们',
    'home.about.desc1': 'Nagato是一家从事开发、设计和提供各种热处理服务的公司，采用现代技术和专家团队，根据国际标准提高材料质量和强度。',
    'home.about.desc2': '凭借提供最佳热处理服务的承诺，我们赢得了全国客户的信任，并准备成为推动您行业成功的一部分。',
    'home.about.cta': '了解更多',
    'home.about.stats.customers': '信任客户',
    'home.about.stats.quality': '质量保证',
    'home.about.stats.support': '支持服务',
    'home.about.stats.experience': '年经验',
    'home.cta.title': '准备开始了吗？',
    'home.cta.description': '加入我们，体验最佳的热处理服务，并获得我们专业团队的支持。',
    'home.cta.button1': '免费开始',
    'home.cta.button2': '联系我们',
    'home.cta.trust': '受领先公司信赖',
    'home.cta.trust1': '汽车工业',
    'home.cta.trust2': '机械工业',
    'home.cta.trust3': '航空航天工业',
    'home.cta.trust4': '能源工业',
    
    // News Section
    'home.news.title': '新闻与更新',
    'home.news.subtitle': '关注热处理技术和公司发展的最新新闻',
    'home.news.readMore': '阅读更多',
    'home.news.viewAll': '查看所有新闻',
    'home.news.item1.title': '最新热处理技术',
    'home.news.item1.description': '公司已实施最先进的热处理技术，以提高工作效率和质量',
    'home.news.item1.category': '技术',
    'home.news.item2.title': '生产能力扩展',
    'home.news.item2.description': '为满足不断增长的需求，公司已扩大生产能力并添加新机械',
    'home.news.item2.category': '新闻',
    'home.news.item3.title': '获得ISO标准认证',
    'home.news.item3.description': '公司获得ISO 9001:2015认证，展示了其对质量服务的承诺',
    'home.news.item3.category': '成就',
    'home.news.item4.title': '参加工业展览',
    'home.news.item4.description': '公司参加工业展览，向客户展示新技术和服务',
    'home.news.item4.category': '活动',
    'home.news.item5.title': '员工安全培训',
    'home.news.item5.description': '为员工进行安全培训，确保每个人的工作场所安全',
    'home.news.item5.category': '员工发展',
    
    // News Page
    'news.pageTitle': '所有新闻',
    'news.pageSubtitle': '关注公司的最新新闻和更新',
    'news.backToHome': '返回首页',
    'news.readMore': '阅读更多',
    'news.close': '关闭',
    'news.item1.title': '最新热处理技术',
    'news.item1.description': '公司已实施最先进的热处理技术，以提高工作效率和质量',
    'news.item1.fullContent': 'NAGATO HEAT TREATMENT (THAILAND) CO.,LTD.已在生产过程中实施最先进的热处理技术，以提高工作效率和质量。这项新技术将有助于提高温度和时间控制的准确性，同时减少能源消耗并提高工作场所安全性。',
    'news.item1.author': '新闻团队',
    'news.item2.title': '生产能力扩展',
    'news.item2.description': '为满足不断增长的需求，公司已扩大生产能力并添加新机械',
    'news.item2.fullContent': '由于业务增长和需求增加，公司决定通过添加新的现代机械和设备以及扩大生产区域来扩大生产能力，以容纳更多客户并按时交付工作。',
    'news.item2.author': '生产部门',
    'news.item3.title': '获得ISO标准认证',
    'news.item3.description': '公司获得ISO 9001:2015认证，展示了其对质量服务的承诺',
    'news.item3.fullContent': '公司获得ISO 9001:2015认证，这是质量管理系统的国际标准。此认证展示了公司提供最高质量服务并提高工作系统效率的承诺。',
    'news.item3.author': '质量部门',
    'news.item4.title': '参加工业展览',
    'news.item4.description': '公司参加工业展览，向客户展示新技术和服务',
    'news.item4.fullContent': '公司参加了重要的工业展览，向客户和商业伙伴展示新技术和服务。此次活动是建立网络和展示公司在热处理方面能力的绝佳机会。',
    'news.item4.author': '营销部门',
    'news.item5.title': '员工安全培训',
    'news.item5.description': '为员工进行安全培训，确保每个人的工作场所安全',
    'news.item5.fullContent': '公司定期为员工进行工作场所安全培训，以确保每个人的安全并降低事故风险。培训涵盖理论和实践应用。',
    'news.item5.author': '安全部门',
    'news.item6.title': '新研发中心开业',
    'news.item6.description': '公司开设新的研发中心，开发热处理创新',
    'news.item6.fullContent': '公司开设了新的现代研发中心，开发热处理创新并创造新技术，这将有助于提高工作效率和产品质量。',
    'news.item6.author': '研发部门',
    'news.item7.title': '大学合作',
    'news.item7.description': '公司与大学在新创新的研究和开发方面合作',
    'news.item7.fullContent': '公司与领先大学签署了在热处理新创新研究和开发方面的合作协议。这种合作将帮助公司获得更多新知识和技术。',
    'news.item7.author': '学术部门',
    'news.item8.title': '年度质量奖',
    'news.item8.description': '公司获得工业协会年度质量奖',
    'news.item8.fullContent': '公司获得工业协会年度质量奖，这是一个展示对提供最高质量服务的承诺和可持续业务发展成功的奖项。',
    'news.item8.author': '管理部门',
    
    // About Page
    'about.hero.business.title': '业务内容',
    'about.hero.business.carburizing': '渗碳淬火 (Carburizing Hardening)',
    'about.hero.business.carbonitriding': '碳氮共渗淬火 (Carbonitriding Hardening)',
    'about.hero.business.quenching': '淬火 (Quenching)',
    'about.hero.business.induction': '感应淬火 (Induction Hardening)',
    'about.hero.business.tempering': '回火 (Tempering)',
    'about.hero.business.and_more': '以及更多',
    'about.hero.certificate.title': '认证',
    'about.hero.certificate.acquisition': '泰国工厂认证获得',
    'about.hero.customer.title': '我们的客户',
    'about.hero.certificate.subtitle': '标准认证',
    'about.hero.certificate.subtitle_en': '(认证)',
    'about.mission.title': '我们的使命',
    'about.mission.main.title': '主要使命',
    'about.mission.main.desc': '致力于提供最高质量的热处理服务，同时通过应用现代技术提高材料质量，为所有客户创造满意。',
    'about.mission.vision.title': '愿景',
    'about.mission.vision.desc': '成为客户信任的热处理行业领导者，通过持续发展和创造新创新来满足不断变化的行业需求。',
    'about.mission.values.title': '价值观',
    'about.mission.values.desc': '精度、责任感和团队合作，以及持续自我发展以提供最佳热处理服务。',
    'about.mission.commitment.title': '我们的承诺',
    'about.mission.commitment.desc': '我们致力于通过提供超出期望的热处理服务并建立长期信任，成为推动您行业可持续发展的组成部分。',
    'about.values.title': '我们的核心价值观',
    'about.values.subtitle': '我们在所有工作中坚持和实践的价值观，为所有客户和员工建立信任和满意。',
    'about.values.quality.title': '质量',
    'about.values.quality.desc': '致力于在每个步骤中提供最高质量的热处理服务',
    'about.values.technology.title': '技术',
    'about.values.technology.desc': '使用由数字系统控制的现代机械和设备',
    'about.values.precision.title': '精度',
    'about.values.precision.desc': '根据国际标准精确控制温度和时间',
    'about.values.reliability.title': '可靠性',
    'about.values.reliability.desc': '保证每个工件的质量和安全',
    'about.values.innovation.title': '创新',
    'about.values.innovation.desc': '通过现代技术和方法持续发展',
    'about.values.excellence.title': '卓越',
    'about.values.excellence.desc': '追求在提供各种热处理服务方面的卓越性',
    'about.values.commitment.title': '我们的承诺',
    'about.values.commitment.desc': '我们致力于以精度、透明度和责任感开展业务，同时持续自我发展以为所有客户提供最佳热处理服务。',
    
    // Service Machinery
    'service.machinery.specifications': '规格',
    'service.machinery.available': '可用数量',
    'service.machinery.carburizing_furnace.title': '渗碳淬火炉',
    'service.machinery.carburizing_furnace.specifications': '760W × 1,200D × 830H (最大1吨)',
    'service.machinery.carburizing_furnace.units': '4台',
    'service.machinery.induction_hardening.title': '感应淬火机',
    'service.machinery.induction_hardening.specifications': '垂直移动式 (最大L=650mm)',
    'service.machinery.induction_hardening.units': '2台',
    'service.machinery.tempering_furnace.title': '回火炉',
    'service.machinery.tempering_furnace.specifications': '760W × 1,200D × 830H (最大650°C)',
    'service.machinery.tempering_furnace.units': '3台',
    'service.machinery.vacuum_degreasing.title': '真空脱脂清洗机',
    'service.machinery.vacuum_degreasing.specifications': '760W × 1,200D × 830H',
    'service.machinery.vacuum_degreasing.units': '1台',
    'service.machinery.automatic_straightening.title': '自动矫直机',
    'service.machinery.automatic_straightening.specifications': '5吨 配备AE传感器 (最大L=600mm)',
    'service.machinery.automatic_straightening.units': '1台',
    'service.machinery.manual_straightening.title': '手动矫直机',
    'service.machinery.manual_straightening.specifications': '1吨 (最大L=600mm)',
    'service.machinery.manual_straightening.units': '2台',

    // Products Page
    'product.hero.title': '热处理服务',
    'product.hero.description': '我们提供各种热处理服务，采用现代技术和专家团队，根据国际标准提高材料质量和强度。',
    'product.hero.heat.title': '热技术',
    'product.hero.heat.desc': '精确的温度控制系统',
    'product.hero.treatment.title': '热处理',
    'product.hero.treatment.desc': '符合国际标准的工艺',
    'product.hero.quality.title': '高质量',
    'product.hero.quality.desc': '每个工件的质量保证',

    'product.showcase.title': '热处理类型',
    'product.showcase.subtitle': '完整的热处理服务，满足各行业需求',
    'product.showcase.annealing.title': '退火',
    'product.showcase.annealing.desc': '退火工艺，降低硬度并改善金属晶体结构',
    'product.showcase.annealing.feature1': '降低金属硬度',
    'product.showcase.annealing.feature2': '改善晶体结构',
    'product.showcase.annealing.feature3': '增加韧性',
    'product.showcase.annealing.feature4': '减少内应力',
    'product.showcase.quenching.title': '淬火',
    'product.showcase.quenching.desc': '淬火工艺，增加硬度和耐磨性',
    'product.showcase.quenching.feature1': '最大硬度增加',
    'product.showcase.quenching.feature2': '耐磨性',
    'product.showcase.quenching.feature3': '增加强度',
    'product.showcase.quenching.feature4': '改善机械性能',
    'product.showcase.tempering.title': '回火',
    'product.showcase.tempering.desc': '回火工艺，减少脆性并平衡硬度与韧性',
    'product.showcase.tempering.feature1': '减少脆性',
    'product.showcase.tempering.feature2': '平衡硬度',
    'product.showcase.tempering.feature3': '增加韧性',
    'product.showcase.tempering.feature4': '减少内应力',
    'product.showcase.normalizing.title': '正火',
    'product.showcase.normalizing.desc': '正火工艺，改善晶体结构和机械性能',
    'product.showcase.normalizing.feature1': '改善晶体结构',
    'product.showcase.normalizing.feature2': '增加强度',
    'product.showcase.normalizing.feature3': '改善机械性能',
    'product.showcase.normalizing.feature4': '减少内应力',
    'product.showcase.carburizing.title': '渗碳',
    'product.showcase.carburizing.desc': '渗碳工艺，增加表面硬度和耐磨性',
    'product.showcase.carburizing.feature1': '增加表面硬度',
    'product.showcase.carburizing.feature2': '高耐磨性',
    'product.showcase.carburizing.feature3': '增加强度',
    'product.showcase.carburizing.feature4': '改善表面性能',
    'product.showcase.nitriding.title': '氮化',
    'product.showcase.nitriding.desc': '氮化工艺，增加表面硬度和耐腐蚀性',
    'product.showcase.nitriding.feature1': '高表面硬度',
    'product.showcase.nitriding.feature2': '耐腐蚀性',
    'product.showcase.nitriding.feature3': '增加强度',
    'product.showcase.nitriding.feature4': '改善表面性能',

    'product.features.title': '我们的特点',
    'product.features.subtitle': '我们通过现代技术和专家团队提供热处理服务，获得最佳结果',
    'product.features.quality.title': '高质量',
    'product.features.quality.desc': '国际质量标准，配备质量证书',
    'product.features.speed.title': '快速',
    'product.features.speed.desc': '按时交付，质量保证',
    'product.features.technology.title': '现代技术',
    'product.features.technology.desc': '由数字系统控制的现代机械和设备',
    'product.features.precision.title': '精度',
    'product.features.precision.desc': '根据国际标准精确控制温度和时间',
    'product.features.support.title': '售后服务',
    'product.features.support.desc': '支持团队24/7随时帮助',
    'product.features.security.title': '安全',
    'product.features.security.desc': '标准安全系统，保证工件安全',

    'product.process.title': '我们的工艺',
    'product.process.subtitle': '清晰、透明和高效的步骤，获得最佳结果',
    'product.process.consultation.title': '咨询与分析',
    'product.process.consultation.desc': '分析需求并定义工作范围',
    'product.process.analysis.title': '检查与分析',
    'product.process.analysis.desc': '热处理前检查材料并分析性能',
    'product.process.treatment.title': '热处理',
    'product.process.treatment.desc': '根据指定标准进行热处理',
    'product.process.quality.title': '质量检查',
    'product.process.quality.desc': '热处理后检查质量并测试性能',
    'product.process.delivery.title': '交付',
    'product.process.delivery.desc': '交付工作，配备测试报告和质量证书',

    'product.parts.title': '我们的零件画廊',
    'product.parts.subtitle': '探索我们高质量制造的零件和组件',
    'product.parts.overview.title': '零件概览',
    'product.parts.overview.desc': '高质量制造的零件',
    'product.parts.part2.title': '精密零件 2',
    'product.parts.part2.desc': '精密设计制造',
    'product.parts.part3.title': '先进零件 3',
    'product.parts.part3.desc': '先进制造技术',

    // Contact Page
    'contact.hero.title': '联系我们',
    'contact.hero.description': '我们准备为您服务并回答您的所有问题。今天就联系我们进行免费咨询。',
    'contact.form.title': '发送消息给我们',
    'contact.form.description': '填写以下信息。我们将在24小时内回复您。',
    'contact.form.name': '姓名',
    'contact.form.name_placeholder': '输入您的姓名',
    'contact.form.email': '邮箱',
    'contact.form.email_placeholder': '输入您的邮箱',
    'contact.form.phone': '电话号码',
    'contact.form.phone_placeholder': '输入您的电话号码',
    'contact.form.company': '公司',
    'contact.form.company_placeholder': '输入您的公司名称',
    'contact.form.position': '职位',
    'contact.form.position_placeholder': '输入您的职位',
    'contact.form.subject': '主题',
    'contact.form.subject_placeholder': '选择您要联系的主题',
    'contact.form.subject_general': '一般询问',
    'contact.form.subject_support': '支持请求',
    'contact.form.subject_sales': '销售询问',
    'contact.form.subject_partnership': '合作',
    'contact.form.subject_other': '其他',
    'contact.form.message': '消息',
    'contact.form.message_placeholder': '输入您要联系的详细信息',
    'contact.form.submit': '发送消息',
    'contact.form.submitting': '发送中...',
    'contact.form.success': '消息发送成功！我们将尽快回复您。',
    'contact.form.error': '发生错误。请重试。',
    'contact.form.error.company': '请输入公司名称',
    'contact.form.error.name': '请输入您的姓名',
    'contact.form.error.email': '请输入邮箱',
    'contact.form.error.email_invalid': '邮箱格式无效',
    'contact.form.error.phone': '请输入电话号码',
    'contact.form.error.position': '请输入您的职位',
    'contact.form.error.message': '请输入消息',
    'contact.info.title': '联系信息',
    'contact.info.description': '您可以通过各种渠道联系我们。我们准备为您服务并回答您的所有问题。',
    'contact.info.email.title': '邮箱',
    'contact.info.email.description': '24小时随时发送邮件给我们',
    'contact.info.phone.title': '电话',
    'contact.info.phone.description': '营业时间内致电我们',
    'contact.info.address.title': '地址',
    'contact.info.address.description': '访问我们的办公室',
    'contact.info.hours.title': '营业时间',
    'contact.info.hours.description': '我们准备服务的时间',
    'contact.info.social.title': '关注我们',
    'contact.map.title': '地图和路线',
    'contact.map.description': '轻松找到来我们办公室的路线',
    'contact.map.placeholder.title': '地图',
    'contact.map.placeholder.description': '地图将在此处显示',
    'contact.map.placeholder.button': '打开地图',
    'contact.map.directions.title': '如何到达',
    'contact.map.directions.bts': 'BTS阿索克 - 6号出口',
    'contact.map.directions.mrt': 'MRT素坤逸 - 3号出口',
    'contact.map.directions.parking': '建筑内停车位',
    'contact.map.nearby.title': '附近地点',
    'contact.map.nearby.terminal21': '航站楼21',
    'contact.map.nearby.emquartier': 'EmQuartier',
    'contact.map.nearby.benjasiri': '班查西里公园',
    'contact.map.nearby.lumpini': '伦披尼公园',
    'contact.company.name': 'NAGATO HEAT TREATMENT (THAILAND) CO.,LTD.',
    'contact.company.address.title': '地址',
    'contact.company.phone.title': '电话',
    'contact.company.hours.title': '营业时间',
    'contact.company.address.detail': '7/379 6号村 阿玛塔市工业区<br />马布扬蓬区 普拉达恩县<br />罗勇府 21140',
    'contact.company.phone.detail': '038-027-473-4<br /><span class="text-sky-600 font-medium">038-027-475 (传真)</span>',
    'contact.company.hours.detail': '周一 - 周五: 07:30 - 16:30<br />周六: 8:00 - 12:00<br />周日: 休息',
    
    // Company Info Section
    'company.title': '长门热处理有限公司',
    'company.subtitle': '(泰国) 有限公司',
    'company.info.title': '公司信息',
    'company.info.address': '地址',
    'company.info.phone': '电话',
    'company.info.established': '成立时间',
    'company.info.address_detail': '7/379 6号村 马布扬蓬区 普拉达恩县 罗勇府 21140 泰国',
    'company.info.phone_detail': '038-027-473-4',
    'company.info.established_detail': '2013年1月',
    'company.quality.title': '质量政策',
    'company.quality.point1': '致力于以真诚生产产品，为客户创造满意',
    'company.quality.point2': '持续改进，为客户提供质量和优质服务',
    'company.slogan.title': '口号',
    'company.slogan.text': '灵活生产',
    
    // 404 Page
    '404.title': '404',
    '404.subtitle': '页面未找到',
    '404.description': '抱歉，您正在寻找的页面不存在或可能已被移动。',
    '404.suggestions': '建议',
    '404.suggestion1': '检查您输入的URL',
    '404.suggestion2': '返回首页',
    '404.suggestion3': '使用上面的导航菜单',
    '404.suggestion4': '如果您认为这是错误，请联系我们',
    '404.backHome': '返回首页',
    '404.contactUs': '联系我们',
  },
};

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const searchParams = useSearchParams();
  const [language, setLanguageState] = useState<Language>('en'); // ตั้งค่าเริ่มต้นเป็นภาษาอังกฤษ

  // ฟังก์ชันสำหรับดึงภาษาจาก localStorage
  const getStoredLanguage = (): Language => {
    if (typeof window !== 'undefined') {
      const stored = localStorage.getItem('nagato-language');
      if (stored && ['th', 'en', 'jp', 'cn'].includes(stored)) {
        return stored as Language;
      }
    }
    return 'en'; // ค่าเริ่มต้นเป็นภาษาอังกฤษ
  };

  // ฟังก์ชันสำหรับเก็บภาษาใน localStorage
  const storeLanguage = (lang: Language) => {
    if (typeof window !== 'undefined') {
      localStorage.setItem('nagato-language', lang);
    }
  };

  // ฟังก์ชันสำหรับอัปเดต URL (ไม่เด้งไปหน้าใหม่)
  const updateUrl = (lang: Language) => {
    const currentPath = window.location.pathname;
    const newUrl = `${currentPath}?lang=${lang}`;
    // ใช้ window.history.replaceState แทน router.replace เพื่อไม่ให้เด้งไปหน้าใหม่
    window.history.replaceState({}, '', newUrl);
  };

  // ฟังก์ชันสำหรับตั้งค่าภาษา
  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    storeLanguage(lang);
    updateUrl(lang);
  };

  // ตรวจสอบภาษาจาก URL หรือ localStorage เมื่อ component mount
  useEffect(() => {
    const urlLang = searchParams.get('lang') as Language;
    
    if (urlLang && ['th', 'en', 'jp', 'cn'].includes(urlLang)) {
      // ถ้ามีภาษาใน URL ให้ใช้ภาษาจาก URL
      setLanguageState(urlLang);
      storeLanguage(urlLang);
    } else {
      // ถ้าไม่มีภาษาใน URL ให้ใช้ภาษาจาก localStorage
      const storedLang = getStoredLanguage();
      setLanguageState(storedLang);
      // อัปเดต URL ให้มีภาษา (ไม่เด้งไปหน้าใหม่)
      updateUrl(storedLang);
    }
  }, [searchParams]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
